### ISSUE TITLE
zfs-0.6.5.7 build failure

### ISSUE THREAD

**Issue by AfoHT** [Antergos/antergos-packages#105]
zfs-0.6.5.7 cannot build due to the most recent change in the zfs package.

commit id: 76b163b35ef76e24b67a339dea3b9529ea935b7b

Please see: [after-todays-update-zfs-module-not-building](https://forum.antergos.com/topic/4551/after-today-s-update-zfs-module-not-building/6)

The addition of the revision and the kernel version in the path tricks DKMS into building modules with that name, and as a side effect requiring SPL to also have those very same revision and kernel version-numbers.

Which breaks the build.

**Comment by lots0logs** [comment]
Hmm...The update went fine on my system. Are you using the standard arch kernel or a custom kernel?

**Comment by AfoHT** [comment]
On Mon, 30 May 2016 10:27:53 -0700
Dustin Falgout <notifications@github.com> wrote:

> Hmm...The update went fine on my system. Are you using the standard
> arch kernel or a custom kernel?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Antergos/antergos-packages/issues/105#issuecomment-222531319

I'm running the standard arch kernel (as per default Antergos install).

Best regards,
Henrik
