### ISSUE TITLE
shutdown button is missing

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/antergos-packages#114]
Please fix or remove [this from installed extensions](https://github.com/Antergos/antergos-packages/tree/master/gnome-shell-extension-status-menu-buttons) by default.

For more information: https://forum.antergos.com/topic/3045/shutdown-button-is-missing-after-upgrade-to-gnome-3-18/4

Thanks.

**Comment by lots0logs** [comment]
Are you sure this is still occurring? I checked and I cannot reproduce it.

**Comment by satriani-vai** [comment]
Yes, this issue occurring on my PC and laprop, and I solved it with deinstallation of gnome-shell-extension-status-menu-buttons.
Anyone can confirm pls?

**Comment by lots0logs** [comment]
Okay well that's not an acceptable "solution". If you could provide the contents of your system journal log after booting while the extension is enabled that would be helpful. :wink:

**Comment by lots0logs** [comment]
Issue moved to [Antergos/gnome-shell-extension-status-menu-buttons #2](https://github.com/Antergos/gnome-shell-extension-status-menu-buttons/issues/2) via [**ZenHub**](https://www.zenhub.com/)
