### ISSUE TITLE
New mirror site in France

### ISSUE THREAD

**Issue by ColtonDRG** [Antergos/antergos-packages#117]
I set up an Antergos mirror and would like to become an authorized mirror.

The mirror's domain is eu.mirrors.coltondrg.com

The mirror's location is Roubaix, France

Right now, it allows access over HTTP, HTTPS, and RSYNC. ~~I'm considering setting up RSYNC, but not yet.~~

https://eu.mirrors.coltondrg.com/antergos/
http://eu.mirrors.coltondrg.com/antergos/
rsync://eu.mirrors.coltondrg.com/antergos

I am syncing from leaseweb.net's Germany mirror at rsync://mirror.de.leaseweb.net/antergos

My email is coltondrg@coltondrg.com

**Comment by lots0logs** [comment]
@ColtonDRG Thanks for contributing a mirror, we appreciate it! Would it be possible for you to go ahead and setup rsync for read only access? Our mirrorbrain sever cannot properly detect the files on your server via `http`. If you would prefer allowing the rsync access only to our mirrorbrain server I can email you the ip address--just let me know!

**Comment by ColtonDRG** [comment]
Sure, I can set it up. I'll do it later today. :)

**Comment by ColtonDRG** [comment]
Alright! I set up rsync. The address is as follows.

rsync://eu.mirrors.coltondrg.com/antergos

**Comment by ColtonDRG** [comment]
@lots0logs This has been idle for almost a week. Is everything OK?

**Comment by lots0logs** [comment]
@ColtonDRG SOrry for the delay. Your mirror has been included on our auto-mirror selection server since the day after you set up rsync. I have been too busy to finish it until now :sweat_smile:

**Comment by ColtonDRG** [comment]
Awesome. Thanks. :)
