### ISSUE TITLE
Become authorized Vietnam mirror

### ISSUE THREAD

**Issue by karibuTW** [Antergos/antergos-packages#118]
Hi there,

I have set up a new mirror for Vietnam, following the wiki: 
https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/

The domain name is: http://mirror.freedif.org/Antergos/
In Vietnam (HCMC)
HTTP connection (Let me know if need rsync or FTP)
I'm using the Tier 1 from US (rsync://mirror.us.leaseweb.net/antergos)
and you can reach me at karibu AT freedif DOT org

Keep up the good work !
Thank you

**Comment by Wyn10** [comment]
@karibuTW Thanks for contributing a mirror, we appreciate it!  Would it be possible for you to go ahead and setup rsync for read only access? Our mirrorbrain sever cannot properly detect the files on your server via ```http```.  If you would prefer allowing the rsync access only to our mirrorbrain server @lots0logs can email you the ip address--just let us know!

**Comment by karibuTW** [comment]
Hi Wyn10, no problem for Rsync
Simply use
rsync://mirror.freedif.org::antergos

Let me know if any issue.

Thanks

**Comment by karibuTW** [comment]
For info you can now access to the mirror statistics here:
http://mirror.freedif.org/Stats/Antergos.html

**Comment by karibuTW** [comment]
After a month, I'm happy to say that Antergos is the project with the highest demand I'm having currently on the mirror. (Close to 500GB in 1 month)
Mainly from India (90GB), Indonesia (50+GB) then Vietnam (40GB)

I hope the speed is good enough.

Let me know if any issue or wish further improvement.

Thank you

Keep up the good work

**Comment by karibuTW** [comment]
Hello,

The VN mirror, mirror.freedif.org, will have a scheduled upgrade the 30th August. I will move facility and move from 100M to 1G connection!

If all goes well, the mirror will be back the 31st August. I will inform you of the success or not of the upgrade.

Karibu

**Comment by karibuTW** [comment]
Hello,
The mirror is not up and running. However I don't see it being much used.
I used to have 50GB+ per day, only got 6GB+ per day now.

Anything to do from your side may be?

Thanks
