### ISSUE TITLE
slight error in the default pulseaudio file

### ISSUE THREAD

**Issue by piratenpanda** [Antergos/antergos-packages#119]
I just found that in the /etc/pulse/default.pa file there is the line:

```
.ifexists module-bluetooth-discover.so
  #load-module module-bluetooth-discover
.endif
```

the comment doesn't make sense to me and prevents my bluetooth headset from working. Maybe someone should take a look and remove the comment

**Comment by Mikaela** [comment]
Pulseaudio doesn't appear to be in this repository, so I would say that this issue is invalid and should be reported either in Arch or if it comes from Pulseaudio, directly to upstream Pulseaudio.

**Comment by piratenpanda** [comment]
Ok, didn't know that, wanted to report in Antergos first. Sry for the noise
