### ISSUE TITLE
Kernel null pointer dereference in broadcom-wl driver

### ISSUE THREAD

**Issue by gokceneraslan** [Antergos/antergos-packages#132]
Please synchronize  broadcom-wl package with the one in AUR. No one using wl driver can boot the system after upgrade to kernel 4.8 due to missing patches in broadcom-wl package. See patches 001 and 004 for kernel 4.8 here https://aur.archlinux.org/cgit/aur.git/tree/?h=broadcom-wl-dkms

**Comment by lots0logs** [comment]
Fixed in 7c9cf2b2a954b14804816390e228d3d97173e44f

**Comment by gokceneraslan** [comment]
Thanks.
