### ISSUE TITLE
Install GNOME Shell Integration by default in Chromium

### ISSUE THREAD

**Issue by slacka** [Antergos/antergos-packages#134]
I love that we default to the Chromium browser and come with many great GNOME Shell Extensions installed such as Dash to Dock. However our defaults are a little inconsistent. [To manage the extensions](https://extensions.gnome.org/) you need the GNOME Shell Integration plugin. 

We install this by default in Firefox, but Firefox is not installed by default. Chromium is, but we do not include this plugin.  So when you go to manage your extensions, you get this error:

> We cannot detect a running copy of GNOME on this system, so some parts of the interface may be disabled. See our troubleshooting entry for more information.

The [PKGBUILD available in the AUR](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation) fixes the issue.

https://aur.archlinux.org/packages/chrome-gnome-shell-git/

**Comment by lots0logs** [comment]
I did not realize that plugin existed! We'll certainly look into it. Thanks for the heads up!

**Comment by Yoshi2889** [comment]
There seem to be stable versions out. I might look into creating an actual package later.
