### ISSUE TITLE
error when updating to numix-icon-theme-square-1:0.r83.3bc6d001-1-any

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#135]
Hi,

Just did a pacman update and got the following error after upgrading numix-icon-theme-square

_gtk-update-icon-cache: The generated cache was invalid_

Thanks

**Comment by karasu** [comment]
If I recall correctly, this was fixed long ago. I just tested it now and works. Please @Swipe650 complain if it does not work for you ;)

Closing.
