### ISSUE TITLE
Add vivaldi-ffmpeg-codecs

### ISSUE THREAD

**Issue by Finnerale** [Antergos/antergos-packages#137]
Without [this](https://aur.archlinux.org/packages/vivaldi-ffmpeg-codecs) package Vivaldi can't play H.264 and MSE.

Also, Vivaldi isn't tagged as a browser [in Antergos repo](http://build.antergos.com/package/vivaldi)

**Comment by karasu** [comment]
Added. Please give it a few hours until all mirrors are updated.
