### ISSUE TITLE
New Mirror

### ISSUE THREAD

**Issue by bolvarak** [Antergos/antergos-packages#138]
Domain:  mirrors.tuxns.net
Country:  US
Protocols:  rsync, http, https
Bandwidth:  1gbps
IPv4:  63.141.252.178
IPv6:  2604:4300:a:3::178
URLs: 
    rsync://mirrors.tuxns.net/antergos
    http://mirrors.tuxns.net/antergos
    https://mirrors.tuxns.net/antergos

Tier 1 Mirror:  mirror.us.leaseweb.net/antergos
Email:  travis[DOT]brown[AT]cdndepo.com

**Comment by lots0logs** [comment]
Thanks @bolvarak ! :smiley:

**Comment by lots0logs** [comment]
@bolvarak It looks like your server isn't accepting requests from [UptimeRobot](https://uptimerobot.com/locations.php). Would you mind looking into it?

**Comment by bolvarak** [comment]
I pushed new DNS changes out, they are currently propagating and should be coming up soon.  They are currently up on Google and Open DNS.
