### ISSUE TITLE
[URGENT] Cinnamon needs to be rebuilt against readline 7

### ISSUE THREAD

**Issue by Yoshi2889** [Antergos/antergos-packages#139]
Cinnamon is built against readline 6 right now and therefore it looks for readline.so.6, however with readline 7 this is no longer shipped, causing Cinnamon to **crash**, making your desktop unusable.

The packages need to be rebuilt against readline 7 to get Cinnamon to work again.

**Comment by karasu** [comment]
@lots0logs 
Also in here:
https://forum.antergos.com/topic/5330/cinnamon-crash-after-login-asus-n550jk/6

I've seen that you're working on Cinnamon 3.2, so I do not dare to rebuild it against readline 7 and "launch" it.
What should we do? Arch is already offering 3.2 (can we release it in spite of some theme problems?).

I'll wait for your answer.

**Comment by Yoshi2889** [comment]
I do kind of want to emphasize that a lot of users are left with broken systems right now and we are getting a lot of support requests for this issue in the IRC channel, so I'd really appreciate it if this could be fixed in a couple of days if possible, if needed with the older version of Cinnamon.

I'm not sure what the reason behind having Cinnamon in the Antergos repo was in the first place, but I'd also consider removing it and relying on the Arch packages instead if it's not required to have them in the Antergos repository.

**Comment by karasu** [comment]
>I'm not sure what the reason behind having Cinnamon in the Antergos repo was in the first place, but I'd also consider removing it and relying on the Arch packages instead if it's not required to have them in the Antergos repository.

Dustin will be able to explain this. What I know is that 3.2 is (was?) buggy with themes and for that, he was waiting to fix it before updating from 3.0 to 3.2

**Comment by lots0logs** [comment]
Sorry guys, its been a really busy day today.  The Cinnamon theme wasn't ready but this readline issue kind of forced my hand so I went ahead and pushed out the updated packages. Mirrors should be synced in a few hours. Cheers!
