### ISSUE TITLE
pepper-flash needs updating

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#141]
Hi, pepper-flash needs updating it's a version behind the one in the aur. I can't use flash websites with this version, it says it's out of date.

**Comment by karasu** [comment]
OK. Thanks!

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/93aa8436784d44cc29db9eb6ccedf6c3ba309f05

**Comment by karasu** [comment]
@Swipe650 as packages are have the same name, you have to remove aur/chromium-pepper-flash before trying to install antergos/chromium-pepper-flash

**Comment by lots0logs** [comment]
@karasu You didn't move it to the repo did you? I'm still waiting on approval from Adobe. I applied weeks ago but they still havent got back to me :grimacing:

**Comment by karasu** [comment]
I just did! Shit. Sorry!

El dl, 21 nov 2016 a les 18:35 Dustin Falgout <notifications@github.com> va
escriure:

**Comment by lots0logs** [comment]
I guess its fine. I really dont think they care much about our use-case anyway ¯\_(ツ)_/¯
