### ISSUE TITLE
Fix Vivaldi's .pkgupdate

### ISSUE THREAD

**Issue by Finnerale** [Antergos/antergos-packages#143]
The [Vivaldi package](https://github.com/Antergos/antergos-packages/tree/master/antergos/vivaldi) needs an update.

The [.pkgupdate](https://github.com/Antergos/antergos-packages/blob/master/antergos/vivaldi/.pkgupdate) doesn't work (and looks a bit hacky), it returns nothing.

This one works for me:
`update_pkgver=$(curl -sS https://vivaldi.com/download/ | grep -i '_amd64.deb' | sed -e 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\-[0-9]\+\).*/\1/')`

To get the version:
`curl -sS https://vivaldi.com/download/ | grep -i '_amd64.deb' | sed -e 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\-[0-9]\+\).*/\1/'`

**Comment by Yoshi2889** [comment]
This file seems to no longer exist; is it still a valid issue?
