### ISSUE TITLE
qt5-styleplugins breaks apps, needs rebuild for Qt 5.7.1

### ISSUE THREAD

**Issue by mdemierre** [Antergos/antergos-packages#147]
qt5-styleplugins needs to be rebuilt with Qt 5.7.1. The current version breaks apps, in my case with qt5ct when using the gtk2 style.

Relevant discussion in Manjaro Forums: https://forum.manjaro.org/t/unstable-qt5-5-7-1-update-breaks-applications/14234/31

The AUR version is already updated: https://aur.archlinux.org/packages/qt5-styleplugins/

**Comment by lots0logs** [comment]
The package was rebuilt a few days ago. You can see the build log [here](http://build.antergos.com/build/5332).

**Comment by mdemierre** [comment]
Sorry about that, is it already in the repo? Because my system was up to date and I still encountered the issue.
