### ISSUE TITLE
Scudcloud needs rebuilding

### ISSUE THREAD

**Issue by Noxbru** [Antergos/antergos-packages#152]
Scudcloud needs to be rebuilt after the python 3.6 -> 3.6 upgrade.

Detected because a person asked about it in the IRC channel.

**Comment by stratus-ss** [comment]
Confirmed. I have been using the version out of the AUR to compensate

**Comment by karasu** [comment]
Fixed by https://github.com/Antergos/antergos-packages/commit/aea104d4c2e619197907236e44941474ccf44f52
