### ISSUE TITLE
Powerpill out of date

### ISSUE THREAD

**Issue by lordtiva** [Antergos/antergos-packages#154]
After the python update powerpill has stopped working.
The current version is 2016.5-3

**Comment by stratus-ss** [comment]
Confirmed. 
This package needs updating

**Comment by karasu** [comment]
Fixed by https://github.com/Antergos/antergos-packages/commit/58d43988465cd43bfe6e8265ef8fd669466e80cf

**Comment by karasu** [comment]
Build fails. Wrong url. Will fix it asap. 😁

**Comment by karasu** [comment]
Done!
