### ISSUE TITLE
[cnchi/cnchi-dev] PKGBUILD files not up to date

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/antergos-packages#156]
I was about to do local test builds and work on changes via git branch and found that none of the 'cnchi' PKGBUILD files are up to date with current package releases.

I hope this is a workflow error.

**Comment by lots0logs** [comment]
Our build server builds cnchi packages automatically based on github activity so the PKGBUILDs dont accurately reflect the state of the package. Also they are expecting to be run on the builder server. I think what we can do to address this is create a PKGBUILD for general use and include it in Cnchi's repo :smiley:

**Comment by philwyettreb** [comment]
PR:

https://github.com/Antergos/antergos-packages/pull/158

Clean up current release PKGBUILD and can be built locally without issue.

Further work to follow.

I have an idea of building all versions of 'cnchi' out of one PKGBUILD file. Just researching logistics and feasibility at present.

**Comment by lots0logs** [comment]
Hmm..actually we need to keep the PKGBUILDs in the repo for now at least. The build server uses them. I think what we should do is add a note that refers developers to the new PKGBUILD in Cnchi's repo for building Cnchi locally.

**Comment by philwyettreb** [comment]
I will just fix them up then.

You can decide on changes to how you want things at a later date.

**Comment by philwyettreb** [comment]
Associated PR is ready to go. No other changes needed at this time.
