### ISSUE TITLE
Brave browser does not start

### ISSUE THREAD

**Issue by almindor** [Antergos/antergos-packages#164]
Brave 0.13.2 from antergos repos does not start on x86_64.

The error is: 

```
FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

It works with the `--no-sandbox` option. Seems to be related to chromium, found a similar report on https://github.com/probonopd/AppImages/issues/81

**Comment by stratus-ss** [comment]
As per the linked thread this is because the kernel does not have user name spaces enabled.

Confirmed by running
```zgrep CONFIG_USER_NS /proc/config.gz```

I dont think weare going to enable that by default. The other option is to use SUID on the binary as the chromium package does

**Comment by stratus-ss** [comment]
@karasu @lots0logs what do you guys think

**Comment by lots0logs** [comment]
Seems to be a [known issue](https://github.com/brave/browser-laptop/issues/6902#issuecomment-277534536)

**Comment by almindor** [comment]
Any news on this? I'd suggest removing brave until this is resolved on the proper level.
