### ISSUE TITLE
[dash-to-dock] 'behaviour' tab out of screen bounds on screen 1366x768

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/antergos-packages#166]
[dash-to-dock] 'behaviour' tab out of screen bounds on screen 1366x768.

![screenshot from 2017-02-16 02-42-50](https://cloud.githubusercontent.com/assets/24805379/23005004/a4bc50e4-f3f1-11e6-9d03-53d8ea20e072.png)

Too tall for screen, no way to scroll down.

**Comment by slacka** [comment]
This is a dupe of https://github.com/micheleg/dash-to-dock/issues/452

The issue was fixed by [this commit.](https://github.com/micheleg/dash-to-dock/commit/73f5c14796cbda8c524cb1c3b60825cb70064141)

**Comment by philwyettreb** [comment]
@slacka This issue was fixed however, it cannot use a clean git patch to rebuild the package due to it being art of a reorganisation already started in previous and future commits.

This is nothing major and will be fixed in next release. Closing.
