### ISSUE TITLE
feedreader wrong installation path?

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#173]
On helping someone with Kernel Panic:
https://forum.antergos.com/topic/6332/kernel-panic-not-syncing-no-working-init-found-after-kernel-update/12

There seems to be a wrong installation path on the Antergos feedreader Package: 

/usr/lib64/FeedReader/ should installed to /usr/lib/FeedReader because /usr/lib64 is a symlink to /usr/lib ????

Take a look to PKGBUILD from AUR and Antergos:

https://github.com/Antergos/antergos-packages/blob/master/antergos/feedreader/PKGBUILD

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=feedreader

**Comment by philwyettreb** [comment]
Attached fixes up the lib64 issue.

* Also fixes 'pkgdir' warning.
* Add two missing deps.
* Drop two unused CMAKE flags.

[update.diff.txt](https://github.com/Antergos/antergos-packages/files/846595/update.diff.txt)

**Comment by killajoe** [comment]
Should be fixed soon caus what happens to BuZZ-dEE was a kernel panic may caused by that package?

**Comment by philwyettreb** [comment]
Fail To Build (FTB), because no '\' at end of line 38.

**Comment by philwyettreb** [comment]
```
==> Checking for packaging issue...
==> WARNING: Package contains reference to $pkgdir
```
Can we also fix the above by changing line 38 to:

`-DCMAKE_INSTALL_PREFIX=/usr \`

and line 46 to:

`make DESTDIR="${pkgdir}" install`

**Comment by karasu** [comment]
Thanks!
