### ISSUE TITLE
new tier2 mirror (mirror.host.ag)

### ISSUE THREAD

**Issue by belcloud** [Antergos/antergos-packages#174]
Hello

We would like to submit our tier 2 mirror.  

Hostname: mirror.host.ag
Location: Sofia, Bulgaria
Access methods: http, ftp, rsync
http://mirror.host.ag/antergos
ftp://mirror.host.ag/antergos
rsync://mirror.host.ag/antergos
Syncing from: mirror.de.leaseweb.net/antergos
Mirror contact: mirror[at]host.ag

Thank you

**Comment by karasu** [comment]
@belcloud Thanks!
