### ISSUE TITLE
[updpkg] GitKraken v2.2.1

### ISSUE THREAD

**Issue by Yoshi2889** [Antergos/antergos-packages#176]
Version 2.2.1 is out: https://support.gitkraken.com/release-notes/current

**Comment by mafzst** [comment]
Nowadays 2.3.3 is out https://support.gitkraken.com/release-notes/current

**Comment by mafzst** [comment]
If I knew it was so simple... Thanks @lots0logs :+1:

**Comment by lots0logs** [comment]
@mafzst at least you'll know next time :wink:
