### ISSUE TITLE
peek package broken

### ISSUE THREAD

**Issue by phw** [Antergos/antergos-packages#180]
The PKGBUILD for peek at https://github.com/Antergos/antergos-packages/blob/master/antergos/peek/PKGBUILD is broken. It sets the `CMAKE_INSTALL_PREFIX` to `${pkgdir}/usr`, but it actually should be `/usr`. This breaks the path used in the DBus service.

The proper way to handle this is to set `CMAKE_INSTALL_PREFIX` to `/usr` (the final installation location) and use `make DESTDIR=${pkgdir} install` for installing. See the PKGBUILD at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=peek

**Comment by phw** [comment]
@lots0logs I just saw you already tried to deal with the launcher issue by commenting out the DBusActivatable . The above changes will fix this cleanly :) And thanks for packaging

**Comment by phw** [comment]
@lots0logs Maybe I am just confused, but I was under the impression this is the PKGBUILD that is used for the official Antergos package. But when I look at http://build.antergos.com/build/6274 either the Antergos build system is a bit stubborn as it did not catch up all the changes from your commit (still using `-DCMAKE_INSTALL_PREFIX="${pkgdir}/usr"`) or it is actually a different PKGBUILD . I am a bit puzzled :)

**Comment by lots0logs** [comment]
Actually, it looks like it's just the diff that is incorrect. The package that was built (and is currently in the main repo) is fine :smiley:

**Comment by phw** [comment]
Thanks for the confirmation, I also got report by users that it is working as expected 👍
