### ISSUE TITLE
Become mirror

### ISSUE THREAD

**Issue by hnt2507** [Antergos/antergos-packages#181]
Mirror domain name: http://mirror.vinahost.vn/
Geographical location of the mirror: Viet Nam - Ho Chi Minh City
Supported access methods (http, ftp, rsync, ...): http, rsync
URLs for the above access methods: http://mirror.vinahost.vn/antergos rsync://mirror.vinahost.vn/antergos
The name of the tier 1 mirror you are syncing from: rsync://mirror.us.leaseweb.net/antergos
An administrative contact email: tienhn@vinahost.vn

**Comment by hnt2507** [comment]
Hello.
Any update about this.
Thanks you.

**Comment by karasu** [comment]
@lots0logs 😁
