### ISSUE TITLE
provides are needed for python xcpf and python xcgf

### ISSUE THREAD

**Issue by SolarAquarion** [Antergos/antergos-packages#183]
: Replace python3-xcgf with antergos/python-xcgf? [Y/n] y
:: Replace python3-xcpf with antergos/python-xcpf? [Y/n] y

:: bauerbill: removing python3-xcgf breaks dependency 'python3-xcgf'
:: bauerbill: removing python3-xcpf breaks dependency 'python3-xcpf'
:: pbget: removing python3-xcgf breaks dependency 'python3-xcgf'
:: pbget: removing python3-xcpf breaks dependency 'python3-xcpf'
:: pm2ml: removing python3-xcgf breaks dependency 'python3-xcgf'
:: pm2ml: removing python3-xcpf breaks dependency 'python3-xcpf'
:: powerpill: removing python3-xcgf breaks dependency 'python3-xcgf'
:: powerpill: removing python3-xcpf breaks dependency 'python3-xcpf'
:: python3-aur: removing python3-xcgf breaks dependency 'python3-xcgf'
:: python3-aur: removing python3-xcpf breaks dependency 'python3-xcpf'

**Comment by lots0logs** [comment]
:facepalm: :laughing:

**Comment by pdf** [comment]
Now I get:
```
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: python-xcgf and python-xcpf are in conflict
```

**Comment by pdf** [comment]
Looks like probably because of this:
https://github.com/Antergos/antergos-packages/blob/84d6d8ab4ed8fc0d5b1facefc4f849f476c3e582/antergos/python-xcpf/PKGBUILD#L14
