### ISSUE TITLE
New mirror (tier2)

### ISSUE THREAD

**Issue by AlpixTM** [Antergos/antergos-packages#188]
Hi,
We would like to submit a new tier 2 mirror.  
Mirror domain name: mirror.alpix.eu
Location: Germany (UTC+2)
Speed: 1Gbit/s
Supported access methods: http(s);rsync
URLs for the above access methods:
https: https://mirror.alpix.eu/antergos/
http: http://mirror.alpix.eu/antergos/
rsync: rsync://mirror.alpix.eu/antergos
The name of the tier 1 mirror I am syncing from: rsync://mirror.de.leaseweb.net/antergos
Administrative contact email: contact[at]alpix.eu

P.S.: To avoid any irritations: My other Mirror(https://antergos-mirror-a.alpix.eu) is hosted on an other Server (85.25.xxx.xx) than this Mirror(85.93.xx.xx).

**Comment by AlpixTM** [comment]
Hello?
Any update about this?
@karasu @lots0logs

**Comment by AlpixTM** [comment]
Hey @lots0logs;

Hey, one of my antergos mirrors will go down soon.

Current situation: I host two mirrors. 
https://antergos-mirror-a.alpix.eu and https://mirror.alpix.eu/antergos.

The server serving "https://antergos-mirror-a.alpix.eu" will go down soon.
Starting from 1.1.2018 (UTC) requests towards "https://antergos-mirror-a.alpix.eu"  will be served by the same server, which is serving "https://mirror.alpix.eu/antergos".

So there's no sense to list both mirrors in the mirrorlist anymore.
So please remove "https://mirror.alpix.eu/antergos" from the mirror list.


I would kindly like to apologize for the inconvenience this may cause.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/266d2d5421f6de939cf093f84e8b6898ef387835
