### ISSUE TITLE
Missing space indicator in Baboba space analysing tool

### ISSUE THREAD

**Issue by orschiro** [Antergos/antergos-packages#19]
With Numix Frost the the coloured space indicator is missing:

![baobab_folder](https://cloud.githubusercontent.com/assets/170947/4537605/3a3a8240-4de0-11e4-9412-530bcdb030bf.png)

In contrast, with the Adwaita theme it is properly displayed:

![screenshot](https://cloud.githubusercontent.com/assets/170947/4537615/79e4cbda-4de0-11e4-965a-2931899c1a22.png)

**Comment by lots0logs** [comment]
Hi, could you please let me know if this issue has been fixed using the latest version of the theme? Thanks.

**Comment by orschiro** [comment]
@lots0logs 

Yes, fixed in `numix-frost-themes 1.3-4`. 

Many thanks!

Robert
