### ISSUE TITLE
gnome-shell-extension-status-menu-buttons is broken

### ISSUE THREAD

**Issue by picsi** [Antergos/antergos-packages#190]
Due to the recent GNOME updates (in particular `gnome-shell-extension-dash-to-dock`, it seems), Status Menu Buttons is no longer working.

**Comment by jvault** [comment]
The package is outdated you just need to update.
# pacman -S gnome-shell-extension-status-menu-buttons

or

Manualy: down github.com/Antergos/antergos-packages/tree/master/antergos/gnome-shell-extension-status-menu-buttons/

.SRCINFO	
PKGBUILD	
buttons.install

And run
# makepgk -sic

I additionally recommend to change it up the pkgbuild, but that is not so relevant:
# Maintainer: Dustin Falgout <dustin@antergos.info>

pkgname=gnome-shell-extension-status-menu-buttons
pkgver=0.4
pkgrel=1
pkgdesc="Adds a hibernate, suspend, & lock button to the status menu."
arch=('any')
url="http://www.antergos.com"
license=('GPLv2')
groups=('gnome-shell-extensions')
depends=('lightdm' 'xscreensaver' 'light-locker')
replaces=('gnome-shell-extension-lockscreen-lightdm')
conflicts=('gnome-shell-extension-lockscreen-lightdm')
install=buttons.install
source=("https://github.com/Antergos/${pkgname}/archive/master.zip")
sha256sums=('854a3c611fb4a36d75a65c82da58e7e7fa320e87c37ae95336a2d6bd5c72183e')

build() {
	cd ${srcdir}
}

package() {
	cd ${pkgdir}
	mkdir -p usr/share/gnome-shell/extensions/status-menu-buttons@dev.antergos.com
	cd usr/share/gnome-shell/extensions/status-menu-buttons@dev.antergos.com
	cp ${srcdir}/${pkgname}-master/extension.js .
	cp ${srcdir}/${pkgname}-master/metadata.json .
	cp ${srcdir}/${pkgname}-master/confirmDialog.js .
}

**Comment by picsi** [comment]
Reinstalling it did the trick for me, thanks!
