### ISSUE TITLE
error: pacaur: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid

### ISSUE THREAD

**Issue by spinktvis** [Antergos/antergos-packages#193]
I am receiving the following error when doing a upgrade of pacaur:

error: pacaur: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid

I have cleared the pacman cache, reinstalled the antergos keyring, and refreshed all the keys, same error persists.

**Comment by spinktvis** [comment]
Tried updating again, and issue was fixed, closing this, and thanks for fixing.

**Comment by karasu** [comment]
Thanks to you for reporting it!
