### ISSUE TITLE
qpdfview package?

### ISSUE THREAD

**Issue by AcarBurak** [Antergos/antergos-packages#196]
A very capable viewer (annotation, highlighting, copying, setting background and foreground colour, synctex synchronization) with minimal dependencies, very fine for any platform, without alternative for a qt5 desktop like lxqt.

**Comment by killajoe** [comment]
This is not an issue or i am wrong?

**Comment by AcarBurak** [comment]
Very sorry, as I've seen a post like that I thought… I'll migrate it (along with the others) to the forum.

**Comment by killajoe** [comment]
you are welcome!

**Comment by AcarBurak** [comment]
Thank you. Thank you for Antergos as well!

**Comment by killajoe** [comment]
Thanks goes to the devs > FORWARD > 
(I am only mod at forum)

**Comment by AcarBurak** [comment]
You're a contributor as well. Another thank for them, then.
