### ISSUE TITLE
Broken: gitkraken 2.5.0-1

### ISSUE THREAD

**Issue by EvanWashkow** [Antergos/antergos-packages#200]
@lots0logs When trying to open a git repository, GitKraken breaks on a "fatal error." After trying to Open an existing repository, GitKraken will load and draw the git log tree (I can see it), then, after several seconds, it will flash a blank, white window and will show a notification that it recovered from a fatal error. Because of the slight delay until the crash, I'm wondering if GitKraken is attempting to perform a network request (possibly to pull in anything from GitHub), but is failing.

I have tried the exact same GitKraken version (on the same git repository) on Xubuntu 17.04, and it works flawlessly. Just wondering if there is a missing dependency or something?

**Comment by maxsu** [comment]
I'm experiencing the same issue. Gitkraken works for repos without remotes, but immediately crashes upon adding a remote or attempting to open a repo with remote.

**Comment by maxsu** [comment]
I've made a [post](https://gitkraken.slack.com/archives/C2DB7B0JG/p1495354395843413) on the gitkraken slack to see if anyone else is having the issue, though I suspect it's our packaging here.

**Comment by maxsu** [comment]
Ah, okay, found a temporary fix: use AUR's package.

It will require you to manually add a GPG key for libcurl-openssl-1.0.

E.g., `$ gpg --recv-keys --keyserver hkp://pgp.mit.edu 5CC908FDB71E12C2`

See discussion at [1] and [2] below.

Refs:
[1] [AUR discussion](https://aur.archlinux.org/packages/libcurl-openssl-1.0/)
[2] [Antergos forum discussion](https://forum.antergos.com/topic/6820/gitkraken-from-the-antergos-repo-is-crashing/4)

**Comment by EvanWashkow** [comment]
@lots0logs could you take a look at this? It looks like you have been the one who has been packaging GitKraken.

**Comment by maxsu** [comment]
It seems like we could easily pull the pkgbuild from AUR.

We may need to debug the libcurl-openssl gpg key issue. It required manual intervention on my machine, and may be Antergos specific.

**Comment by EvanWashkow** [comment]
I can confirm the GPG issue is NOT Antergos specific. The same issue exists on Manjaro.

I agree. It would be much better to pull the build from AUR. There's no point, and its broken several times before usder the Antergos builds.

**Comment by EvanWashkow** [comment]
Just switched to Manjaro. Because, at least, they care enough to make sure that stuff works / not doing extraneous proprietary software builds.

**Comment by EvanWashkow** [comment]
@maxsu how do you install from AUR instead of the (broken) Antergos package builds? Every time I search for the package "gitkraken", I don't see the option in AUR in Pacman. Maybe I have to use yaourt?

**Comment by EvanWashkow** [comment]
* Pamac

**Comment by maxsu** [comment]
@EvanWashkow I thought you had made your way to Manjaro, loool! Teasing aside, you are correct about yaourt. Do

> yaourt gitkraken

and you'll see something like

```
1 antergos/gitkraken 2.6.0-1 (development)
    The intuitive, fast, and beautiful cross-platform Git client.
2 aur/gitkraken 2.6.0-2 [installed: 2.6.0-1] (149) (10.03)
    The intuitive, fast, and beautiful cross-platform Git client.
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 
```

**Comment by EvanWashkow** [comment]
I did. But, I'm hating how much they control my system. I just want to let Arch be Arch. (Kinda like how I'd like phone developers to leave Android, Android).

Thanks for that. I'm gonna give that a whirl and see if I can get Antergos back.
