### ISSUE TITLE
gtk-theme-adapta broken signature

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#201]
https://forum.antergos.com/topic/6929/gtk-theme-adapta-update-install-broken-for-weeks

**Comment by karasu** [comment]
<img width="476" alt="captura de pantalla 2017-05-19 a les 12 17 32" src="https://cloud.githubusercontent.com/assets/175797/26243853/a46ee95a-3c8d-11e7-92f9-cda6c96384b7.png">

**Comment by killajoe** [comment]
Thanks to @karasu to solve this
