### ISSUE TITLE
Cinnamon problems after an update

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#204]
I had several problems with my cinnamon. I thought it is something I done but after fresh install I stil have the same issues.
Here is the list of them:

names of icons don’t show on desktop; of course you can rename them
shortcut for volume up is broken - the bar goes far beyond the borders
shortcut for brightness doesn’t work at all
Source: https://forum.antergos.com/topic/6946/cinnamon-problems-after-an-update/2

**Comment by lots0logs** [comment]
Those bugs would need to reported upstream as its very unlikely to be a packaging issue. However, if it turns out I'm wrong we can reopen this at that time.
