### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by othpiik** [Antergos/antergos-packages#206]
> 
[root@Oh-Notebook oh]# pacman -Syu
:: Synchronizing package databases...
 antergos is up to date
 core is up to date         0.0   B  0.00B/s 00:00 [----------------------]   0%
 extra is up to date        0.0   B  0.00B/s 00:00 [----------------------]   0%
 community is up to date    0.0   B  0.00B/s 00:00 [----------------------]   0%
 multilib is up to date     0.0   B  0.00B/s 00:00 [----------------------]   0%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (47) alsa-lib-1.1.4-1  alsa-plugins-1.1.4-1  alsa-utils-1.1.4-1
              apache-2.4.25-3  atom-1.17.0-1  btrfs-progs-4.11-1
              clementine-1.3.1-8  cups-filters-1.14.0-1  ffmpeg-1:3.3.1-8
              ffmpeg2.8-2.8.11-9  firefox-53.0.3-1  gnome-maps-3.24.3-1
              gnome-menus-3.13.3+27+g69656ff-1  gst-plugins-ugly-1.12.0-3
              gtksourceview3-3.24.2-1  hwids-20170328-1  imagemagick-6.9.8.6-1
              jasper-2.0.13-1  lib32-alsa-lib-1.1.4-1  lib32-libdrm-2.4.80-1
              lib32-lm_sensors-3.4.0-1  lib32-mesa-17.1.0-1  libgadu-1.12.2-3
              libibus-1.5.16-1  libphonenumber-8.4.1-3
              libx264-2:148.20170121-6  libx264-all-2:148.20170121-6
              linux-4.11.2-1  linux-firmware-20170422.ade8332-1
              linux-headers-4.11.2-1  lm_sensors-3.4.0-2  mesa-17.1.0-1
              mesa-vdpau-17.1.0-1  npth-1.4-1  numix-icon-theme-1:0.r1942-1
              pango-1.40.6+6+g6f59d0f3-2  postgresql-libs-9.6.3-1
              protobuf-3.3.1-1  protobuf-c-1.2.1-6  python-cairo-1.13.1-1
              python-requests-2.14.2-1  python2-cairo-1.13.1-1
              qt5-declarative-5.8.0-2  speech-dispatcher-0.8.7-1
              virtualbox-host-modules-arch-5.1.22-3  vlc-2.2.5.1-1
              xfsprogs-4.11.0-1

Total Download Size:   256.52 MiB
Total Installed Size:  943.76 MiB
Net Upgrade Size:       82.55 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 numix-icon-theme-1:...     3.6 MiB  1110K/s 00:03 [######################] 100%
 hwids-20170328-1-any     340.2 KiB  1668K/s 00:00 [######################] 100%
 btrfs-progs-4.11-1-...   597.3 KiB  2.22M/s 00:00 [######################] 100%
 linux-firmware-2017...    41.9 MiB  5.34M/s 00:08 [######################] 100%
 linux-4.11.2-1-x86_64     61.3 MiB  5.91M/s 00:10 [######################] 100%
 linux-headers-4.11....     7.4 MiB  5.28M/s 00:01 [######################] 100%
 npth-1.4-1-x86_64         13.6 KiB  4.41M/s 00:00 [######################] 100%
 xfsprogs-4.11.0-1-x...   813.5 KiB  2.81M/s 00:00 [######################] 100%
 alsa-lib-1.1.4-1-x86_64  459.0 KiB  2022K/s 00:00 [######################] 100%
 alsa-plugins-1.1.4-...    62.6 KiB  1044K/s 00:00 [######################] 100%
 alsa-utils-1.1.4-1-...   950.0 KiB  1684K/s 00:01 [######################] 100%
 apache-2.4.25-3-x86_64  1426.3 KiB   300K/s 00:05 [######################] 100%
 libx264-2:148.20170...   369.8 KiB  1761K/s 00:00 [######################] 100%
 lm_sensors-3.4.0-2-...   124.8 KiB  1015K/s 00:00 [######################] 100%
 mesa-17.1.0-1-x86_64      13.0 MiB  4.37M/s 00:03 [######################] 100%
 ffmpeg-1:3.3.1-8-x86_64    8.2 MiB  5.15M/s 00:02 [######################] 100%
 pango-1.40.6+6+g6f5...   429.7 KiB  2046K/s 00:00 [######################] 100%
 jasper-2.0.13-1-x86_64   289.6 KiB   620K/s 00:00 [######################] 100%
 protobuf-3.3.1-1-x86_64 1416.3 KiB  6.01M/s 00:00 [######################] 100%
 imagemagick-6.9.8.6...     2.2 MiB   299K/s 00:08 [######################] 100%
 cups-filters-1.14.0...   753.1 KiB  2.48M/s 00:00 [######################] 100%
 ffmpeg2.8-2.8.11-9-...     5.8 MiB  5.18M/s 00:01 [######################] 100%
 firefox-53.0.3-1-x86_64   43.9 MiB  5.94M/s 00:07 [######################] 100%
 libphonenumber-8.4....  1322.9 KiB  3.13M/s 00:00 [######################] 100%
 gnome-maps-3.24.3-1...   578.1 KiB  2.26M/s 00:00 [######################] 100%
 gnome-menus-3.13.3+...   136.0 KiB  6.64M/s 00:00 [######################] 100%
 libx264-all-2:148.2...   511.4 KiB  2.13M/s 00:00 [######################] 100%
 gst-plugins-ugly-1....   233.3 KiB  1397K/s 00:00 [######################] 100%
 gtksourceview3-3.24...   964.2 KiB  3.01M/s 00:00 [######################] 100%
 protobuf-c-1.2.1-6-...    86.7 KiB  1354K/s 00:00 [######################] 100%
 libgadu-1.12.2-3-x86_64   95.3 KiB  1489K/s 00:00 [######################] 100%
 libibus-1.5.16-1-x86_64    3.2 MiB  4.50M/s 00:01 [######################] 100%
 mesa-vdpau-17.1.0-1...  1610.2 KiB  6.05M/s 00:00 [######################] 100%
 postgresql-libs-9.6...  1089.9 KiB  5.91M/s 00:00 [######################] 100%
 python-cairo-1.13.1...    37.6 KiB  3.67M/s 00:00 [######################] 100%
 python-requests-2.1...   154.2 KiB  1254K/s 00:00 [######################] 100%
 python2-cairo-1.13....    37.7 KiB   712K/s 00:00 [######################] 100%
 qt5-declarative-5.8...     3.3 MiB  4.59M/s 00:01 [######################] 100%
 speech-dispatcher-0...   427.0 KiB  1857K/s 00:00 [######################] 100%
 vlc-2.2.5.1-1-x86_64      10.0 MiB  5.32M/s 00:02 [######################] 100%
 atom-1.17.0-1-x86_64      19.5 MiB  5.42M/s 00:04 [######################] 100%
 clementine-1.3.1-8-...     5.1 MiB  4.84M/s 00:01 [######################] 100%
 virtualbox-host-mod...   181.2 KiB  1362K/s 00:00 [######################] 100%
 lib32-alsa-lib-1.1....   364.7 KiB  1880K/s 00:00 [######################] 100%
 lib32-libdrm-2.4.80...   135.2 KiB  6.60M/s 00:00 [######################] 100%
 lib32-lm_sensors-3....    23.5 KiB  7.66M/s 00:00 [######################] 100%
 lib32-mesa-17.1.0-1...    12.7 MiB   305K/s 00:43 [######################] 100%
(47/47) checking keys in keyring                   [######################] 100%
(47/47) checking package integrity                 [######################] 100%
error: numix-icon-theme: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is unknown trust
:: File /var/cache/pacman/pkg/numix-icon-theme-1:0.r1942-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

[root@Oh-Notebook oh]# pacman -Syu
:: Synchronizing package databases...
 antergos is up to date
 core is up to date         0.0   B  0.00B/s 00:00 [----------------------]   0%
 extra is up to date        0.0   B  0.00B/s 00:00 [----------------------]   0%
 community is up to date    0.0   B  0.00B/s 00:00 [----------------------]   0%
 multilib is up to date     0.0   B  0.00B/s 00:00 [----------------------]   0%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (47) alsa-lib-1.1.4-1  alsa-plugins-1.1.4-1  alsa-utils-1.1.4-1
              apache-2.4.25-3  atom-1.17.0-1  btrfs-progs-4.11-1
              clementine-1.3.1-8  cups-filters-1.14.0-1  ffmpeg-1:3.3.1-8
              ffmpeg2.8-2.8.11-9  firefox-53.0.3-1  gnome-maps-3.24.3-1
              gnome-menus-3.13.3+27+g69656ff-1  gst-plugins-ugly-1.12.0-3
              gtksourceview3-3.24.2-1  hwids-20170328-1  imagemagick-6.9.8.6-1
              jasper-2.0.13-1  lib32-alsa-lib-1.1.4-1  lib32-libdrm-2.4.80-1
              lib32-lm_sensors-3.4.0-1  lib32-mesa-17.1.0-1  libgadu-1.12.2-3
              libibus-1.5.16-1  libphonenumber-8.4.1-3
              libx264-2:148.20170121-6  libx264-all-2:148.20170121-6
              linux-4.11.2-1  linux-firmware-20170422.ade8332-1
              linux-headers-4.11.2-1  lm_sensors-3.4.0-2  mesa-17.1.0-1
              mesa-vdpau-17.1.0-1  npth-1.4-1  numix-icon-theme-1:0.r1942-1
              pango-1.40.6+6+g6f59d0f3-2  postgresql-libs-9.6.3-1
              protobuf-3.3.1-1  protobuf-c-1.2.1-6  python-cairo-1.13.1-1
              python-requests-2.14.2-1  python2-cairo-1.13.1-1
              qt5-declarative-5.8.0-2  speech-dispatcher-0.8.7-1
              virtualbox-host-modules-arch-5.1.22-3  vlc-2.2.5.1-1
              xfsprogs-4.11.0-1

Total Download Size:     3.58 MiB
Total Installed Size:  943.76 MiB
Net Upgrade Size:       82.55 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 numix-icon-theme-1:...     3.6 MiB   931K/s 00:04 [######################] 100%
(47/47) checking keys in keyring                   [######################] 100%
(47/47) checking package integrity                 [######################] 100%
error: numix-icon-theme: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is unknown trust
:: File /var/cache/pacman/pkg/numix-icon-theme-1:0.r1942-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

**Comment by killajoe** [comment]
```
pub  rsa4096/CDBD406AA1AA7A1D
     created: 2014-08-04  expires: 2019-05-10  usage: SC  
     trust: full          validity: unknown
sub  rsa4096/5F916D2943567287
     created: 2014-08-04  expired: 2017-05-23  usage: E   
[ unknown] (1). Antergos Build Server (Automated Package Build System) <admin@antergos.org>
```
sub key expired on yesterday....

https://forum.antergos.com/topic/6962/numix-icon-theme-signature-is-unknown-trust/5

**Comment by lots0logs** [comment]
Please see: https://antergos.com/wiki/system-admin/package-management/update-error-involving-keyrings/
