### ISSUE TITLE
after upgrade latest version  linux-headers-4.11.2-1 .. my WiFi notworking anymore

### ISSUE THREAD

**Issue by othpiik** [Antergos/antergos-packages#208]
after upgrade latest version  linux-headers-4.11.2-1 .. my WiFi notworking anymore

and try to reinstall kernel then got this message : 
`
[root@Oh-Notebook build]# sudo pacman -S linux linux-headers
warning: linux-4.11.2-1 is up to date -- reinstalling
warning: linux-headers-4.11.2-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) linux-4.11.2-1  linux-headers-4.11.2-1

Total Installed Size:  118.17 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                                        [######################################] 100%
(2/2) checking package integrity                                      [######################################] 100%
(2/2) loading package files                                           [######################################] 100%
(2/2) checking for file conflicts                                     [######################################] 100%
(2/2) checking available disk space                                   [######################################] 100%
:: Running pre-transaction hooks...
(1/1) Remove DKMS modules
==> dkms remove broadcom-wl/6.30.223.271 -k 4.11.2-1-ARCH
Error! There is no instance of broadcom-wl 6.30.223.271
for kernel 4.11.2-1-ARCH (x86_64) located in the DKMS tree.
:: Processing package changes...
(1/2) reinstalling linux                                              [######################################] 100%
>>> Updating module dependencies. Please wait ...
(2/2) reinstalling linux-headers                                      [######################################] 100%
:: Running post-transaction hooks...
(1/3) Install DKMS modules
==> dkms install broadcom-wl/6.30.223.271 -k 4.11.2-1-ARCH
Error! Bad return status for module build on kernel: 4.11.2-1-ARCH (x86_64)
Consult /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log for more information.
(2/3) Updating linux initcpios
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> Starting build: 4.11.2-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
==> Starting build: 4.11.2-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: wd719x
==> WARNING: Possibly missing firmware for module: aic94xx
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
==> Image generation successful
(3/3) Arming ConditionNeedsUpdate...

`

how to fixed thus issue , please?

**Comment by ElDanteDelAnte** [comment]
I am having almost exactly this same issue. I was hoping further updates would solve it, but it's a no-go. Same thing happens with just
`sudo pacman -S broadcom-wl`
I've tried refreshing keyrings, populating the keys, updating lts-headers, and much else. Still nothing.

Let me know if you track down a solution. If I beat you to it, I'll post it here.

**Comment by karasu** [comment]
@lots0logs , I can confirm it.
```
==> dkms install broadcom-wl/6.30.223.271_4.11.2_1 -k 4.12.8-2-ARCH
Error! Bad return status for module build on kernel: 4.12.8-2-ARCH (x86_64)
Consult /var/lib/dkms/broadcom-wl/6.30.223.271_4.11.2_1/build/make.log for more information.
(2/2) Arming ConditionNeedsUpdate...
```
As you have updated that package, I'll leave it to you. If you want me to do it, tell me, please.

@ElDanteDelAnte while we fix this, you can use `broadcom-wl-dkms` package instead.

**Comment by ElDanteDelAnte** [comment]
@karasu I literally just found out that fix and came here to share it with you!

Glad to hear you were able to solve it, too.
