### ISSUE TITLE
Feedreaders source list is empty

### ISSUE THREAD

**Issue by pyriand3r** [Antergos/antergos-packages#209]
The antergos package of feedreader seems broken as it is not possible to choose a feed source. The list to choose from is simply empty. 

I am using Gnome Shell allthough i don't think this is case here. 

The AUR package of feedreader works without problems (after removing .local/share/feedreader)

**Comment by karasu** [comment]
@pyriand3r sorry for the delay. It's been a long time that feedreader is maintained in Arch community repository (I'm sure you already figured this out). We are not maintaining it anymore.

Closing.
