### ISSUE TITLE
Cinnamon 90_antergos.gschema.override configuration needs updated?

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#213]
`==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
==> Image generation successful
Compiling GSettings XML schema files...
No such key 'scroll-method' in schema 'org.cinnamon.settings-daemon.peripherals.touchpad' as specified in override file '/usr/share/glib-2.0/schemas/90_antergos.gschema.override'; ignoring override for this key.
No such key 'keyboard-applet-use-flags' in schema 'org.cinnamon' as specified in override file '/usr/share/glib-2.0/schemas/90_antergos.gschema.override'; ignoring override for this key.
error parsing key 'overview-corner' in schema 'org.cinnamon' as specified in override file '/usr/share/glib-2.0/schemas/90_antergos.gschema.override': 0-5:can not parse as value of type 'as'.Ignoring override for this key.
Updating icon theme caches...
Creating temporary files...
Arming ConditionNeedsUpdate...
Updating the info directory file...
Updating the desktop file MIME type cache...
Transaction successfully finished.`

From here:
https://forum.antergos.com/topic/7224/no-such-key-update-errors/6

**Comment by lots0logs** [comment]
Issue moved to [Antergos/antergos-gsettings #1](https://github.com/Antergos/antergos-gsettings/issues/1) via [**ZenHub**](https://www.zenhub.com/)
