### ISSUE TITLE
Update mate-tweak to latest version

### ISSUE THREAD

**Issue by ThanosApostolou** [Antergos/antergos-packages#214]
Please update **mate-tweak** to the latest version 17.10.7. Better use also the latest ubuntu-mate-settings version 17.10.11 for the pkgbuild.

I don't have time to test, but you may need also to update **mate-desktop** to a newer version in order to avoid segfaults when changing panel layouts, see for example Stefano's (manjaro's mate maintainer) commit: https://github.com/manjaro/packages-community/commit/105335fd4da0c83d8aec2ae5d6e8349efafbb84f

**Comment by lots0logs** [comment]
The 17.x series is a development series. The latest stable series is 16.x. We only package the latest stable version in our repos. Sorry!

**Comment by ThanosApostolou** [comment]
Actually that's not true. The 16.10 series have reached EOL. At manjaro and AUR, as well as opensuse tumbleweed the 17.10.x series are used already and they are working greate, because when a new release is out, then the previous doesn't get any bugfixes or anything anymore. If you don't want to use 17.10.x series, then at least, in my opinion, better use the 17.04.2 which is the latest "stable". The 16.10 is outdated.

**Comment by lots0logs** [comment]
Sorry I misunderstood what this issue was about. I see now that MATE Tweak tool is using Ubuntu version scheme instead of the version scheme of the MATE Desktop stack. I didn't realize it at first and I based what I told you off of the version you mentioned. The current stable version of MATE Desktop stack is actually 1.18.x and that is what is currently in our repositories. I will look further into the tweak tool. Sorry for the confusion.

**Comment by ThanosApostolou** [comment]
Yeah unfortunately mate-tweak is not part of mate project, but is maintained by wimpy alone (I believe they should make it part of the official project, sine it's pretty distro-agnostic but anyway).

Just make sure that after you build it, to try to change some panel layouts and make sure you don't get any error:
```
(mate-tweak:1759): GLib-GIO-ERROR **: Settings schema 'org.mate.interface' does not contain a key named 'gtk-shell-shows-menubar'
Trace/breakpoint trap (core dumped)
```

If you get this error, then a newer version of **mate-desktop** is needed, which can be easily done if you see the manjaro's commit on the initial comment (I believe the fix will be backported some day to a mate-desktop point release but I'm not sure).
