### ISSUE TITLE
[Tool request] rssguard

### ISSUE THREAD

**Issue by vdun** [Antergos/antergos-packages#216]
https://github.com/martinrotter/rssguard

AUR:
https://aur.archlinux.org/packages/rssguard/
https://aur.archlinux.org/packages/rssguard-git/

**Comment by karasu** [comment]
Hi,

Sorry for the delay. As you may found out, rssguard is in the Arch community repository. There is no need for us to maintain it at this point. Again, sorry we didn't answer this before.

Thanks!
