### ISSUE TITLE
[Tool request] FeedReader

### ISSUE THREAD

**Issue by vdun** [Antergos/antergos-packages#217]
https://github.com/jangernert/FeedReader

AUR:
https://aur.archlinux.org/packages/feedreader/
https://aur.archlinux.org/packages/feedreader-beta/
https://aur.archlinux.org/packages/feedreader-git/

**Comment by logos88** [comment]
Package needs to be fixed

https://github.com/jangernert/FeedReader/issues/504

**Comment by karasu** [comment]
There is already a feedreader version in Arch community repository, we will not be adding this package in our repo anymore. Thanks!
