### ISSUE TITLE
Broken: GitKraken

### ISSUE THREAD

**Issue by MateuszKubuszok** [Antergos/antergos-packages#220]
After last update GitKraken in Antergon has the same issue that AUR recently solved: https://github.com/Azd325/gitkraken/issues/45. I believe the same fix could be applied here.

**Comment by CHBMB** [comment]
Awesome, been waiting for this issue that you referenced to be solved.

**Comment by MaxSchambach** [comment]
Yes, me too.
The problem has been solved in version 2.7.0-2.
Current version in AUR is 2.7.1-1 so an update of the Antergos repo would be very nice!

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/6f6d33a173108fb03fe1ca3fe5e705dafec59309

**Comment by CHBMB** [comment]
@karasu Thank you very much!
