### ISSUE TITLE
[Package Request] [Gnome Shell Extensions] Dash to Panel

### ISSUE THREAD

**Issue by gg-berdzenishvili** [Antergos/antergos-packages#221]
https://github.com/jderose9/dash-to-panel
https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel/

I am not sure if it is an appropriate way to ask to add a new package. Please let me know about the appropriate one if this should not be done this way.

**Comment by karasu** [comment]
Hi @gg-berdzenishvili , that's ok.

As this extension is gaining popularity, I've accepted your suggestion. Dash-to-dock will continue to be the default, though.

Added in [this commit](https://github.com/Antergos/antergos-packages/commit/58a5da79016d391f77ccce2d417686f1b3154fb0)

Cheers!

**Comment by gg-berdzenishvili** [comment]
Thanks!
