### ISSUE TITLE
[Package Request] Skype for Linux WebRTC Beta (new skype client for Linux)

### ISSUE THREAD

**Issue by gg-berdzenishvili** [Antergos/antergos-packages#222]
https://aur.archlinux.org/packages/skypeforlinux-bin/

This package is popular enough. Should it be included into Antergos repo?

**Comment by killajoe** [comment]
Yes true it is popular, but it is almost the same then using skype inside webbrowser (WebApp).
I do not think that installing this will give a big benifit.

**Comment by gg-berdzenishvili** [comment]
Yes, it is almost the same. But the main and only advantage is its tray icon and ability to be autostarted that is useful when skype is used as a corporate messenger.

**Comment by karasu** [comment]
We're sorry but as @killajoe commented it's not worth the effort. Closing.
