### ISSUE TITLE
liblastfm-qt5-1.1.0.r637-1 is corrupt (invalid GPG signature)

### ISSUE THREAD

**Issue by igungor** [Antergos/antergos-packages#223]
Up-to-date Antergos. Tried to install tomahawk and couldn't since liblastfm-qt5 is can't be installed.

No VPN, no proxy whatsoever. Here is the full log:

https://gist.github.com/igungor/80a97c7feb3b966f7565c4841d9eee2b

Refreshed GPG keys, removed unused repos, and still can’t install liblastfm-qt5.

**Comment by killajoe** [comment]
i can confirm here

**Comment by elvirolo** [comment]
Me too.

**Comment by karasu** [comment]
@lots0logs do you know what's causing this?

**Comment by killajoe** [comment]
In the meantime you can still use the PKGBUILD from the AUR....

**Comment by elvirolo** [comment]
But its development has been abandoned: see https://github.com/tomahawk-player/tomahawk

**Comment by killajoe** [comment]
Then it should be removed instead of investigate to much time in this ...
