### ISSUE TITLE
Question: RX 550, what driver use

### ISSUE THREAD

**Issue by nyancat18** [Antergos/antergos-packages#226]
1 What driver should i use with a RX 550?
2 antegos install it all out the box (for let me use the rx 550 with blender)
3 should i buy other GPU?

i plan buy this GPU

**Comment by karasu** [comment]
@nyancat18 this is not really an issue but a question, right? Could you be so kind and post a thread in our forum? It's in forum.antergos.com

Thanks for your understanding!
