### ISSUE TITLE
Powerpill missing dependency 

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#228]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/Powerpill.py", line 36, in <module>
    import pm2ml
  File "/usr/lib/python3.6/site-packages/pm2ml.py", line 33, in <module>
    import XCPF
  File "/usr/lib/python3.6/site-packages/XCPF/__init__.py", line 4, in <module>
    from .common import *
  File "/usr/lib/python3.6/site-packages/XCPF/common.py", line 38, in <module>
    import MemoizeDB
ModuleNotFoundError: No module named 'MemoizeDB'
```
The package needs **python3-memoizedb** but this is not aviable as a package only at AUR ???
I can see her  after installing it powerpill works...

**Comment by karasu** [comment]
We used powerpill some time ago... with the old CLI installer, I think. That's why we haven't maintained it. That must be a new dependency. Let me check this

**Comment by karasu** [comment]
@killajoe Could you please remove python3-memoizedb and try this one? It worked here:
https://repo.antergos.info/iso/testing/uefi/antergos-staging/x86_64/powerpill-2017-2-any.pkg.tar.xz

**Comment by killajoe** [comment]
https://repo.antergos.info/iso/testing/uefi/antergos-staging/x86_64/powerpill-2017-2-any.pkg.tar.xz
404 Not Found ;)

**Comment by karasu** [comment]
Sorry! I just moved it to stable. Here it is:
http://repo.antergos.com/antergos/x86_64/powerpill-2017-2-any.pkg.tar.xz

**Comment by killajoe** [comment]
try but same error, without python3-memoizedb

**Comment by killajoe** [comment]
python3-xcgf is not in Antergos Repo?

**Comment by karasu** [comment]
python-xcgf is Antergos' one, python3-xcgf is AUR's. We follow Arch naming, so python3 packages are named python* while python2 packages are named python2*

So, please, remove AUR packages and try again, because I have no python3 AUR packages here and it works ;)

**Comment by killajoe** [comment]
try also at a virtual upto date openbox installation and result in the same error as at my first post here sorry!

**Comment by killajoe** [comment]
solved, great job!
