### ISSUE TITLE
Not getting Antergos updates

### ISSUE THREAD

**Issue by BlueGoliath** [Antergos/antergos-packages#231]
Hi,

I'm not getting package updates for anything in this repo anymore. I did randomly get an update notification from pamac about an update to both pamac and Vivaldi 1.11 but attempting to download them did nothing(they went away, actually...) and I am still stuck on the following pamac and Vivaldi versions:

Vivaldi: 1.10.867.48-2
Pamac: 4.9.1-1

I tried doing a bunch of thing suggested on the forum but still no updates from this repo. Is there anyway to resolve this?

Thanks!

**Comment by killajoe** [comment]
sudo pacman -Syu
From a terminal

**Comment by BlueGoliath** [comment]
Just tried that, didn't do anything.

**Comment by killajoe** [comment]
This is not a bug with a package so your question should go to the forum... (https://forum.antergos.com)

**Comment by killajoe** [comment]
take  a look to /etc/pacman.conf   and /etc/pacman.d/antergos-mirrorlist.
make shure Antergos is on top of repos inside pacman.conf

**Comment by killajoe** [comment]
https://sourceforge.net/projects/antergos/files/mirror/antergos/x86_64/antergos-mirrorlist-20170527-2-any.pkg.tar.xz/download  manual download the new mirrorlist package and install with 

pacman -U antergos-mirrorlist-20170527-2-any.pkg.tar.xz

**Comment by BlueGoliath** [comment]
Ah, wasn't sure if this was an issue with the repo itself or not. 

/etc/pacman.conf has Antergos at the top. antergos-mirrorlist has several Antergos servers with the first being sourceforge yet i'm still not getting anything.

**Comment by killajoe** [comment]
i am only a user too ;)  there is a kind of a problem with Antergos Repo, but your question is not related to packages, it is related to a problem with updating and this should be discussed at the forum....
Go here to read about the repo prob. this is may effecting you?
https://forum.antergos.com/topic/7808/error-failed-retrieving-file-antergos-db-from-mirrors-antergos-com
