### ISSUE TITLE
GitKraken issue

### ISSUE THREAD

**Issue by pavlepiramida** [Antergos/antergos-packages#233]
One provided here fails to work,
while aur/gitkraken works as expected.
I tried pulling aur/gitkraken deps and installing antergos/gitkraken over it ,but it still fails to work.

I can start antergos/gitkraken without any issues,log in to git
but as soon as I load up local repo or cloned one,it starts to fail (gitkraken starts restarting itself).

**Comment by karasu** [comment]
Thanks for reporting it! We'll try to update the package asap

**Comment by karasu** [comment]
@faidoc I updated this so it uses libcurl-openssl-1.0 I hope it's ok....

**Comment by faidoc** [comment]
@karasu sure, no problem, I see it has problems with the other one.

**Comment by karasu** [comment]
@pavlepiramida I've updated it. Tell us if you have any problems with the Antergos version.

**Comment by pavlepiramida** [comment]
I apologize for late reply,but yes,everything is working on my side regarding antergos/gitkraken!
Thanks for the fast fix and version bump!
