### ISSUE TITLE
Authorized mirror request

### ISSUE THREAD

**Issue by zdykstra** [Antergos/antergos-packages#234]
Hi all,

I've added Antergos to a mirror host I manage. 

Mirror domain name: mirrors.servercentral.com
Geographical location: Chicago, IL, United States
Supported access methods: HTTP
URL: http://mirrors.servercentral.com/antergos/
Tier 1 sync host: rsync://mirror.us.leaseweb.net/antergos
Administrative contact e-mail: zdykstra@servercentral.com

Rsync command used:

`rsync --verbose --recursive --times --links --delay-updates --delete-after --hard-links --ignore-times rsync://mirror.us.leaseweb.net/antergos/ /storage/mirrors/pub/antergos/`

The machine in question is on a 10GE connection with ~300TB of space.  Please let me know if you need any additional information, or if there are any issues in my mirror setup that need to be addressed.

**Comment by zdykstra** [comment]
Is the documentation at https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/ not accurate? I'm a little surprised that a mirror request has sat for three weeks with no response.

**Comment by karasu** [comment]
Hi,

Sorry for the delay. Our member that always adds mirrors to our mirrorlist is really busy with other matters. I'll add it to the list myself this time (@lots.0.logs I hope it's ok).

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/448afc306e1e4c01623866590acd809d6077bf63

**Comment by zdykstra** [comment]
No worries, I completely understand that people get really busy!

**Comment by lots0logs** [comment]
Need to add to mirrorbrain. Will do it asap.
