### ISSUE TITLE
Pamac AUR support fills /tmp, does not clean up

### ISSUE THREAD

**Issue by ypnos** [Antergos/antergos-packages#235]
When using AUR support, and trying to build a large package from AUR, this can happen:

- During building or packaging, the 2 GB virtual filesystem on `/tmp` fills up
- The build aborts with, when lucky, the corresponding error (no space left on disk)
- Nothing is cleaned up, so now all future builds or other software using `/tmp` fail, often with strange errors

I experienced this with a fresh install from antergos 17.9 ISO, trying to build `aur/phpstorm` package.

**Comment by killajoe** [comment]
This is caused by the use of tmpfs, /tmp is inside Ram. You can change yaourtrc to use temp directory inside your home

**Comment by ypnos** [comment]
Thank you for the information. I used `pacaur` instead to install the AUR package.

I just wanted to point out that for a better default user experience, it might be a good measure to automatically clean up the data produced in `/tmp`. It seems to build up if you install several packages.  Also, such a failure should not lead to consecutive failures.

**Comment by killajoe** [comment]
The main problem is that the space is limited with the size of your RAM.

**Comment by killajoe** [comment]
And me too i think pacaur is the better one as it is more clean and secure.

**Comment by Warmuser** [comment]
I have a similar problem, sometimes I can't install every AUR package till I restart the Distro. Also If I restart Pamac before the Distor restart. After It run perfectly. I got 16GB of Ram.

**Comment by karasu** [comment]
As @killajoe said, yaourt uses /tmp as default. You can change it in /etc/yaourtrc ( change it to TMPDIR="/var/tmp" for instance).

There was some discussion to change yaourt for pacaur, but never reached a final decision.
