### ISSUE TITLE
pluma package does not install dependencies

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#238]
https://forum.antergos.com/topic/7914/bug-with-pacman/5
[trace](https://ptpb.pw/VWkF)

**Comment by karasu** [comment]
@lots0logs our `pluma` package does not pull mate-desktop, so installing `pluma` leaves you with a non working editor (it doesn't start). Is that on purpose? 

Oh, and now it seems that Arch is packaging Mate gtk3 finally, and they're are par with us (same version). Should we stop packaging Mate? I really don't remember why we started doing it in the first place.

**Comment by karasu** [comment]
@lots0logs ?
