### ISSUE TITLE
Blank screen with jetbrains-toolbox package

### ISSUE THREAD

**Issue by t0ngt0n9** [Antergos/antergos-packages#240]
Hello,

I've installed the lastest version of jetbrains-toolbox, but 
when I launch it, I have a blank screen.
I'm on XFCE. So, how can I resolve this ?

**Comment by lots0logs** [comment]
If you exit the app and then restart it again it should work. The first time it starts after updating a patch is applied to work-around the blank screen issue.

**Comment by t0ngt0n9** [comment]
I still have the problem after trying your solution.
But when I launch it from the command line with `--disable-seccomp-filter-sandbox` option, it works.

**Comment by jwatsonlegalserver** [comment]
Same experience as reported by t0ngt0n9; exiting and restarting the app does not resolve this particular issue. Adding the `--disable-seccomp-filter-sandbox` option is a good work-around.
