### ISSUE TITLE
jetbrains-toolbox warnings 

### ISSUE THREAD

**Issue by pavlepiramida** [Antergos/antergos-packages#243]
Was bored a little and took a look around antergos/ ,installed jetbrains-toolbox and got this 

(1/1) installing jetbrains-toolbox                 [######################] 100%
cp: cannot create regular file '/home/lost+found/.config/autostart/jetbrains-toolbox.desktop': No such file or directory
chmod: cannot access '/home/lost+found/.config/autostart/jetbrains-toolbox.desktop': No such file or directory
chmod: cannot access '/home/lost+found/.local/share/applications/jetbrains-toolbox.desktop': No such file or directory

Im guessing PKGBUILD needs tweaking?
Dunno,but I wanted to report it just in case!

**Comment by killajoe** [comment]
/home/lost+found/ looks kinda wrong to me...

**Comment by killajoe** [comment]
is working fine here: https://i.imgur.com/IdU8wqr.png

**Comment by pavlepiramida** [comment]
@killajoe I didnt choose any user name,that warring is prompt on install,not on launch.
It launches normal and I can download brains products without any issues,but install created lost+found in /home,beside my user.
