### ISSUE TITLE
Error loading dash-to-dock extension

### ISSUE THREAD

**Issue by takias** [Antergos/antergos-packages#247]
I have recently installed Antergos-17.10-minimal-iso. After installation I can see the dash-to-dock is not working properly. The `Show Applications` button does not respond, changing settings doesn't take effect. Under Tweaks > Extension I can see an exclamation sign saying `error loading extension`.

Is it because version 1:60-1 does not support GNOME 3.26?

![screenshot from 2017-10-07 08-17-53](https://user-images.githubusercontent.com/11479802/31304121-6ed3ac4e-ab38-11e7-89a3-9e8891327e75.png)

**Comment by killajoe** [comment]
new version for dash-to-dock is on the way!
https://build.antergos.com/package/gnome-shell-extension-dash-to-dock
