### ISSUE TITLE
Include recent pamac fixes

### ISSUE THREAD

**Issue by bastimeyer** [Antergos/antergos-packages#248]
The update function of pamac seems to be broken in its current `6.0.3` release. You're basically not being notified of any updates after refreshing the repos when using this version and you have to directly use pacman instead. See here:
https://github.com/manjaro/pamac/issues/331
https://github.com/manjaro/pamac/issues/334

Since pamac hasn't published a new release yet, packagers are encouraged to include patches for now (or build from one of the latest commit IDs of the master branch). The pamac package in the AUR (pamac-aur) has already done that and bumped its pkgrel number:
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=pamac-aur

Could you please do the same here? Having a broken package manager helper that doesn't report any updates is quite confusing and people who are currently using the broken pamac package of the antergos repo should be notified that they have to update manually. Thanks.

**Comment by killajoe** [comment]
Confirmed at the Forum too, as many users reporting the same issue!

**Comment by karasu** [comment]
But should we package a "patched" version? It seems quite "ugly", to say the least. Why they do not release a functional version? Well... this package is maintained by @lots0logs , so I won't change it unless he instructs me to do so because he has no time to do it and he agrees to do it.

Sorry.

**Comment by karasu** [comment]
https://github.com/manjaro/pamac/issues/336

**Comment by killajoe** [comment]
so this one can be closed as pamac is working now!

**Comment by bastimeyer** [comment]
Closing the thread, but users of 6.0.3 should be notified of their broken package manager helper...
