### ISSUE TITLE
[antergos-midnight-timers] missing daemon-reload

### ISSUE THREAD

**Issue by Rahtgaz** [Antergos/antergos-packages#249]
A post-install `systemctl daemon-reload` will both reload the unit files configuration and immediately set the new timers, without the need for the user to reload the daemon himself or to reboot.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/10a3221541be59b3e10c7e7d3a0d0820e592ce9e

This is the first time I deal with a systemd service modification. I hope doing it this way it's ok.

**Comment by Rahtgaz** [comment]
Well, it is the automatic starting or restarting of services post-installation that is not advisable. Although, some may be obvious exceptions.

You have a better option of adding a pacman hook. This way, if more than one package updates systemd unit config files, they won't all call their own daemon-reload.

```
# /usr/share/libalpm/hooks/systemd-local-config-reload.hook
[Trigger]
Type      = File
Operation = Install
Operation = Upgrade
Operation = Remove
Target    = etc/systemd/system/*

[Action]
Description = Local configuration changed. Systemd daemon reloading...
When        = PostTransaction
Exec        = /usr/bin/systemctl daemon-reload
Depends     = systemd
```

Notice that I am only adding the local configuration path to `Target`. This is intentional. New units installed to `/usr/lib/systemd/system` should behave as they always did. We only want to deal with the special case.

Alternatively, if you are still uncomfortable about it, the coolest and safest bet is to just add a textual reminder for the user and refuse to do it yourself.

```
Systemd local configuration changed.
Please either invoke `sudo systemctl daemon-reload` or reboot, for changes to take effect.
```
