### ISSUE TITLE
cinnamon 3.6.0 crash

### ISSUE THREAD

**Issue by gkatev** [Antergos/antergos-packages#253]
Hello, after updating to cinnamon 3.6.0, it will fail to start. Attempting to manually start it will show the following error:
```
(cinnamon:3083): Clutter-ERROR **: ClutterBoxLayout child StBin natural width: 0.000000 < minimum 1.000000 
for height 42.000000
```

I reported the [issue](https://github.com/linuxmint/Cinnamon/issues/6989) to the cinnamon repository, they guess that it may be due to a packaging error.

**Comment by lots0logs** [comment]
Have you tried disabling your applets/extensions? You can do that by moving the extensions into another directory temporarily. You can find them in `~/.local/share/cinnamon`

**Comment by gkatev** [comment]
Yes, the culprit was an applet. Sorry for the confusion.
