### ISSUE TITLE
Error: the certificate of mirrors.tux.systems is not trusted

### ISSUE THREAD

**Issue by spinktvis** [Antergos/antergos-packages#254]
Today I received the following error when doing pacman -Syyu

Error: the certificate of mirrors.tux.systems is not trusted.
Hasn't got a known issuer.
Was signed using an insecure algorithm.
The certificate owner does not match hostname.

This is one of the Antergos mirrors (Server = http://mirrors.tuxns.net/antergos/$repo/$arch). 

I'm holding off on updating until somebody can confirm.

**Comment by t14462** [comment]
Same error.
SSL certificate problem: self signed certificate

**Comment by spinktvis** [comment]
I've removed the server from the mirrorlist as a work around for now. I hope one of the devs can respond, there have been to many certificate hacks and server compromises in the last years around the globe to just let this pass. You can't ever be careful enough.

**Comment by karasu** [comment]
@lots0logs do you have this mirror owner? We could warn him if this is still happening...
