### ISSUE TITLE
antergos-kde-meta (Dependecy Hell)

### ISSUE THREAD

**Issue by t14462** [Antergos/antergos-packages#255]
I want to remove Transmission and VLC (because I have Tixati and SMPlayer) without removing entire system.

1. CORE-components (mesa, Qt, systemd) from *-meta package must be installed as DEPENDENCIES
2. User's software (Transmission, VLC etc) must be installed as POST-INSTALL script, not as dependencies.

**Comment by lots0logs** [comment]
You can simply remove the meta package without removing any other packages that you wish to keep.

**Comment by t14462** [comment]
Thanx, Cpt. but it works "so simply" only in Pamac (which require working X11/Wayland session).

After this simple operation do something like that: yaourt -Qdt  — and you have ruined system.

Dependencies != Post-Install.

**Comment by lots0logs** [comment]
I'm not sure what you mean. Removing a meta package does not remove the packages it depends on.

**Comment by karasu** [comment]
@lots0logs if you remove "orphans" with `pacman -Rns $(pacman -Qtdq)` all packages that were installed because of `antergos-blahblalbah-meta` will be removed as well. That's the problem with removing the meta package.

**Comment by lots0logs** [comment]
Well yes, of course..but removing orphans is not a requirement. Plus if one wants to do it anyway they just need to mark the packages as explicitly installed before doing so. I know its possible but I don't know of the top of my head the necessary command(s) to do it. TBH, I don't think this is something to worry about. Its an edge case that most users will never encounter.

**Comment by karasu** [comment]
Yes, I just was trying to explain what I think @t14462 meant. But I agree.

**Comment by nivaca** [comment]
I understand what t14462 means. What I do is simply `sudo pacman -Rdd transmission-qt`, which means: remove package and don't worry about dependencies (in this case `antergos-kde-meta`).
