### ISSUE TITLE
Touchpad is not working properly in Antergos 17.11 Gnome

### ISSUE THREAD

**Issue by kahoooo** [Antergos/antergos-packages#257]
Natural scrolling is not working even I set the option in setting to on.
Two-finger tap become middle click instead of right click.
Three-finger tap become right click.

After googling, I found the problem to be `xf86-input-synaptics` installed alongside `xf86-input-libinput`.
I tried to remove xf86-input-synaptics by
`sudo pacman -S xf86-input-synaptics`
But `xf86-input-synaptics` is required by `antergos-common-meta` so I can't remove it simply by the above command. So I tried
`sudo pacman -Rdd xf86-input-synaptics`
and it solves the problem.

However, I got the following error message now every time I install a new package.
> error: missing 'xf86-input-synaptics' dependency for 'antergos-common-meta'

**Comment by karasu** [comment]
Thanks. We'll fix it asap creating a new release for antergos-common-meta

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/f801d28fdaed0f33009ff0b1522cbe3aaae8d027
