### ISSUE TITLE
authorized mirror request hungary

### ISSUE THREAD

**Issue by infothu** [Antergos/antergos-packages#259]
Hi, im Peter Makk from Infotronik Kft.,

I would like to inform You that we have started a new Antergos mirror.

Mirror domain name
http://mirror.infotronik.hu  (78.131.56.189)

Geographical location of the mirror
Hungary

Supported access methods (http, ftp, rsync, ...)
http

Only serves IPv4 connections.
We do not provide rsync or FTP service.

Our mirror has a 200Mb/s intra- and the same international
upload bandwidth. (we also accept connections from other countries,
regions and do not limit their bandwidth).

URLs for the above access methods
http://mirror.infotronik.hu/mirrors/pub/antergos/

The name of the tier 1 mirror you are syncing from.
mirror.de.leaseweb.net/antergos/ 

An administrative contact email
mirror@infotronik.hu

Other info:

mirror's operator:
Infotronik Kft.

URL of the mirror's operator:
https://infotronik.hu

The name and contact address of the mirror operator:
Peter Makk
mirror@infotronik.hu

**Comment by karasu** [comment]
Thanks a lot! Sorry for the delay.
https://github.com/Antergos/antergos-packages/commit/f13de4f52b267de5478b10059be24f0d06703773

@lots0logs this needs to be added to mirrorbrain, too?
