### ISSUE TITLE
antergos-kde-setup causing update dependency conflict error!

### ISSUE THREAD

**Issue by wolkenschieber** [Antergos/antergos-packages#266]
On upgrade `antergos-kde-setup` is reporting missing dependencies:
```
:: antergos-kde-setup: requires kdenetwork-kopete
:: antergos-kde-setup: requires kdeutils-sweeper
```
This is similar to issue #264.

**Comment by karasu** [comment]
How does this differ from #264 ?

**Comment by wolkenschieber** [comment]
#264 deals with `antergos-kde-meta`, but see this has been fixed with #265.

**Comment by wolkenschieber** [comment]
The package hasn't reached the mirrors yet. This is probably because it fails to build due to some invalid hash signatur. This [gist](https://gist.github.com/wolkenschieber/35dfc966d6f6ba0dc118d89465f499ab) contains a patched `PKGBUILD` for `antergos-kde-setup-1.1-4`, which works for me.

**Comment by piomiq** [comment]
And links to the rest required to build files:
https://github.com/Antergos/antergos-packages/blob/master/antergos/antergos-kde-setup/.SRCINFO
https://github.com/Antergos/antergos-packages/blob/master/antergos/antergos-kde-setup/antergos-kde-setup.install
As you see both coming from branch master. Thanks above I was able to build "antergos-kde-setup".

**Comment by wolkenschieber** [comment]
Thanks @piomiq. I've added the files to the [gist](https://gist.github.com/wolkenschieber/35dfc966d6f6ba0dc118d89465f499ab).

**Comment by JimSangwine** [comment]
I'm still running into this problem trying to install antergos-kde-setup:

```bash
sudo pacman -Ss antergos-kde-setup 
antergos/antergos-kde-setup 1.0-3
```

```bash
sudo pacman -S antergos-kde-setup 
warning: cannot resolve "kdenetwork-kopete", a dependency of "antergos-kde-setup"
warning: cannot resolve "kdeutils-sweeper", a dependency of "antergos-kde-setup"
:: The following package cannot be upgraded due to unresolvable dependencies:
      antergos-kde-setup

:: Do you want to skip the above package for this upgrade? [y/N]
```

Is there a timeline for when this fix might make it into production?

Thanks!

**Comment by wolkenschieber** [comment]
The package `antergos-kde-setup` is deprecated and replaced by `antergos-kde-meta`. See [this thread](https://forum.antergos.com/topic/8698/updating-issue-with-libkexiv2-dependencies/14) for details.

So the solution is to:
1. Remove package `antergos-kde-setup` with keeping the dependencies
2. Install package `antergos-kde-meta`

The procedure is described in the threads:
* [Updating issue with libkexiv2 dependencies](https://forum.antergos.com/topic/8698/updating-issue-with-libkexiv2-dependencies)
* [computer won't update](https://forum.antergos.com/topic/8764/computer-won-t-update)
