### ISSUE TITLE
package grub2-editor not working

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#267]
* Installed the package and it do not show up over applications (KDE Plasma) ..
trying to open with : kcmshell4 kcm_grub2 give me this:

https://picload.org/view/ddgoiorr/screenshot_20171219_121936.png.html

optional dependency: kdebase-workspace is now only aviable over AUR

**Comment by karasu** [comment]
I think this piece of software is long deprecated... Latest version is dated 05/06/2015

I wouldn't bother with it.

@lots0logs can you remove it from our repository?
