### ISSUE TITLE
we need gnome-shell-extension-topicons+PLUS !

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#268]
As i can see we need https://github.com/phocean/TopIcons-plus to get **pamac-tray** visible under Gnome 3.26!
https://extensions.gnome.org/extension/1031/topicons/

The "normal" topicons https://extensions.gnome.org/extension/495/topicons/ seems not to work under Archbased systems?

**Comment by lots0logs** [comment]
The extension in our repo is topicons-plus. You can check the PKGBUILD if you like :wink:

**Comment by karasu** [comment]
Ups... thanks for deleting the one I pushed.
