### ISSUE TITLE
Missing package in default plasma install

### ISSUE THREAD

**Issue by kgleason** [Antergos/antergos-packages#269]
All,
  I'm not sure if this is the appropriate place to file this issue or if it is somewhere upstream. If not, please feel free to point me in the right direction. 
  I recently did a brand new Antergos install with a Plasma desktop. I had an issue when I went to configure a network printer using the Plasma printer settings (System Settings -> Printers).
  When the dialog box opened to add the URL for the printer, I got the following error message: 

    Failed to group devices: 'The name org.fedoraproject.Config.Printing was not provided by any .service files'

  I would get that message whether I was using Jet Direct or IPP for the printing protocol.
  I resolved the issue by installing `system-config-printer` from the extra repository.
  It seems like it might be a missing dependency?

**Comment by karasu** [comment]
Hi,
system-config-printer is installed if "printing" feature is selected in the installer (cnchi).

Cheers!
