### ISSUE TITLE
Authorized mirror request

### ISSUE THREAD

**Issue by johnstruse** [Antergos/antergos-packages#270]
- Mirror domain name: **antergos.mirror.constant.com**
- Geographical location of the mirror: **New Jersey, USA**
- Supported access methods (http, ftp, rsync, ...): **http, https, rsync**
- URLs for the above access methods:
  - http://antergos.mirror.constant.com
  - https://antergos.mirror.constant.com
  - rsync://antergos.mirror.constant.com/antergos/
- The name of the tier 1 mirror you are syncing from: **mirror.us.leaseweb.net**
- An administrative contact email: **mirrors@constant.com**

Mirror is IPv6 enabled and has a 10Gb/s network connection.

**Comment by karasu** [comment]
Added! sorry for the delay.
https://github.com/Antergos/antergos-packages/commit/d0bfbda2094def5ebd4b47b3cc93dd668af6091b
