### ISSUE TITLE
Octopi needs updating

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#278]
Octopi has recently been updated to fix a octopi icon tray synchronisation issue since some qt5 packages were updated

AUR Packages: octopi-0.8.5-3  octopi-cachecleaner-0.8.5-3  octopi-notifier-qt5-0.8.5-3  octopi-pacmanhelper-0.8.5-3  octopi-repoeditor-0.8.5-3

**Comment by CurtisBelt** [comment]
According to the [changelog](https://github.com/aarnt/octopi/blob/master/CHANGELOG) and the [releases](https://github.com/aarnt/octopi/releases) on the Octopi repo, the latest version is v0.8.1. And v0.9.0 is in development.

The aur package is customized and a "fake" pkgver is being used, which is probably not the best idea to be repeating. Check out the comments here: https://aur.archlinux.org/pkgbase/octopi/?comments=all

There is a octopi-git package which I believe is supposed to be taking the latest commits - you'll have to test that out for yourself though, I didn't dig deeper. It's version is correctly marked as 0.8.1.
