### ISSUE TITLE
Authorized mirror request

### ISSUE THREAD

**Issue by rroethof** [Antergos/antergos-packages#280]
Mirror domain name: mirror.neostrada.nl
Geographical location of the mirror: Dronten, Flevoland, The Netherlands
Supported access methods (http, ftp, rsync, ...): http, https, ftp, rsync
URLs for the above access methods:
http://mirror.neostrada.nl/antergos/
https://mirror.neostrada.nl/antergos
ftp://mirror.neostrada.nl/antergos/
rsync://mirror.neostrada.nl/antergos/
The name of the tier 1 mirror you are syncing from: mirror.nl.leaseweb.net
An administrative contact email: mirror@neostrada.nl
Mirror is IPv6 enabled and has a 100Mb/s public connection.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/72315167cea26e0eed48f9467b071cd817367935
