### ISSUE TITLE
antergos-deepin-meta dependency dissatisfaction

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#284]
seem that gnome-software needs packagekit to be able to work for arch-packages or more detailed [gnome-software-packagekit-plugin](https://www.archlinux.org/packages/community/x86_64/gnome-software-packagekit-plugin/) ? what have it as a dependency ?

I would say it is a better idea to remove this from deepin-meta deps and use pamac as adwaita (non-dual ;) ) package manager ?

link to discussion on forum:
https://forum.antergos.com/topic/9046/software-app-empty/6

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/0ed34c8716bd2dc86622c75272c87fd53a7d0721
