### ISSUE TITLE
antergos-deepin-meta needs update dep change

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#285]
link to disussion on forum: https://forum.antergos.com/topic/9070/could-not-satisfy-dependencies-error/2

Looks like that **deepin-artwork-themes**  is replaced by community/**deepin-desktop-schemas**
But **antergos-deepin-meta** has **deepin-artwork-themes** as dependency and update today fails by this issue.
I am not 100% sure here so i will not try to do a pull request.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/0ed34c8716bd2dc86622c75272c87fd53a7d0721

Thanks!

**Comment by killajoe** [comment]
fixed! and thank you karasu!!!
