### ISSUE TITLE
defaults: nautilus.desktop should be org.gnome.Nautilus.desktop

### ISSUE THREAD

**Issue by goodmami** [Antergos/antergos-packages#299]
This is related to an issue I filed in antergos-desktop-settings (https://github.com/Antergos/antergos-desktop-settings/issues/2)

It looks like this repository is where the xdg default for `inode/directory` is set to `nautilus.desktop` (specifically, [here](https://github.com/Antergos/antergos-packages/blob/master/antergos/antergos-gnome-defaults-list/defaults.list#L221)). On my system (Gnome 3.26.2), I have `/usr/share/applications/org.gnome.Nautilus.desktop`, but not `nautilus.desktop`. Perhaps the defaults needs to be changed (for `inode/directory` and a number of other mime types)?

Furthermore, `defaults.list` is deprecated, and it should be merged with `mimeapps.list`. See the [Arch wiki](https://wiki.archlinux.org/index.php/Default_applications#XDG_standard) and [XDG standard](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html).

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/52206f5337745136be9ee4ca84f60e99e5c93e09

Thanks!
