### ISSUE TITLE
pamac 6.2.5-2 app-info path missing (pamac-tray.desktop)

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#301]
Error warning from journal:
`pamac-tray.desktop [27995]: /usr/share/app-info/icons/archlinux-arch-antergos/64x64/mate-utils_mate-disk-usage-analyzer.png: file »/ usr / share / app-info /icons/archlinux-arch-antergos/64x64/mate-utils_mate-disk-usage-analyzer.png «Could not open: file or directory not found`

```
ls /usr/share/app-info/icons/         
archlinux-arch-community  archlinux-arch-core  archlinux-arch-extra
```

**Comment by lots0logs** [comment]
This is actually a bug in Pamac and needs to be reported there. It needs to check if appstream data exists for a repo before attempting to use it.
