### ISSUE TITLE
[Question] How do you upgrade packages directly with [ANTBS]?

### ISSUE THREAD

**Issue by CurtisBelt** [Antergos/antergos-packages#305]
For example, I occasionally send in PR's to update the GitKraken package.

* Is it possible for me to use ANTBS to update the package instead of a PR?
* Are the ANTBS package upgrade commits being automated somehow, or are they manually done by someone behind the scenes?

Thanks!

**Comment by lots0logs** [comment]
The build system is backed by this repo. To manually initiate build you have to commit to the master branch (or submit a PR and have one of us merge it). There are many packages that are monitored by the build server and automatically built when there's a new release. You can tell if a package has the release monitor enabled by checking its profile page (for example: https://build.antergos.com/package/peek)

**Comment by CurtisBelt** [comment]
Ah, got it. Thanks for the info!
