### ISSUE TITLE
numix icon themes need an update

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#308]
the default numix square icontheme missing icon naming changes from latest GNOME 3.28 update, numix-square-icons-git from aur already include them, looks like the already add changes upstream.

**Comment by karasu** [comment]
@lots0logs it's not a packaging problem. It's that some icons got renamed by Gnome.
Like this one:
https://github.com/numixproject/numix-core/commit/3430c20dec118c29a90e348694c44602370c2d4f

**Comment by killajoe** [comment]
@lots0logs  numix-square-icon-theme-git is using updates directly from git:
`source=('numix-square-icon-theme::git+https://github.com/numixproject/numix-icon-theme-square.git')`
as far as i do understand  ;)

**Comment by killajoe** [comment]
https://build.antergos.com/package/numix-icon-theme
