### ISSUE TITLE
vivaldi 1.15.1147.36 is out ...

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#317]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vivaldi

https://vivaldi.com/blog/vivaldi-1-15-just-better/

vivaldi 1.15.1147.36

* Upgraded Chromium to 65.0.3325.183

I will create pull request later...

**Comment by killajoe** [comment]
It seems that it do not build anymore with the renewed PKGBUILD, it gives me "error 404" on chromium source download...
I can get when i do change chromium Version from  65.0.3325.183-1 to 65.0.3325.183
And it is still not in the build queue ? Or is it failing somewhere?

**Comment by karasu** [comment]
Hi,
The "renewed" PKGBUILD... which one is it? The one in AUR or the one in antergos-packages? Can you share it? @lots0logs is who knows this PKGBUILD, though.

**Comment by killajoe** [comment]
the one from Antergos/antergos-packages ;)

**Comment by killajoe** [comment]
But may i am not on same versioning at my local repo...  
I try now to build with same as at Antergos/antergos-packages from github...

**Comment by killajoe** [comment]
checksum changed:
`md5sums=('c7d271f76140c891b1b6e96ae4b3b71c'
         'b6318ddd70f1b31f71511cbd49603c7c'
         '3d06df0bcdb32ab37b89466dd4c0132b'
         '65c1f3c6893b31db816d594ba5591956'
         'a9e07c22ce941c58e8885405c082ea50'
         '6bf54d3ceeec5f13ba68b0ef74db9e20'
         '254061cb349cff714230b7cca83b0a4c'
         '95535a28e5041183ef715c7daa476732')`

**Comment by killajoe** [comment]
```
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/home/joekamprad/Dokumente/GitHub/antergos-packages/antergos/vivaldi/src/../vivaldi-widevine-helper': No such file or directory
==> ERROR: A failure occurred in package().

```

**Comment by killajoe** [comment]
latest version is aviable over Antergos repo :)
