### ISSUE TITLE
Error updating antergos-wallpapers-extra

### ISSUE THREAD

**Issue by akawaka** [Antergos/antergos-packages#322]
Received the following error while attempting to update the antergos-wallpapers-extra package:

```
error: antergos-wallpapers-extra: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid
:: File /var/cache/pacman/pkg/antergos-wallpapers-extra-0.4-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by karasu** [comment]
Fixed. 0.4-2 is ok. Please give it a few hours until the package is updated in all of them.

@lots0logs @killajoe 

https://github.com/Antergos/antergos-packages/commit/7e062c8b63efbdf1a2258778d076f0f2fa1803dd#commitcomment-28972064
