### ISSUE TITLE
antergos-deepin-meta include non existing dependency deepin-wm-switcher

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#327]
antergos-deepin-meta package, includes deepin-wm-switcher but this is not longer aviable at Archlinux Repositories, it is replaced by startdde as you can see at its PKGBUILD:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/startdde

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/pull/326

**Comment by killajoe** [comment]
package is still not updated on the mirrors > buildserver problem?

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/issues/814#issuecomment-392374573
