### ISSUE TITLE
tilix package causes signature error and fails to install

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#329]
`error: tilix: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid
:: File /var/cache/pacman/pkg/tilix-1.7.9-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`

**Comment by karasu** [comment]
Thanks @killajoe !

https://github.com/Antergos/antergos-packages/commit/b7a25cd6441086a4804cc91a37bfc1721ef404df

**Comment by killajoe** [comment]
gitkraken too :(

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/de5e394669f3ad864d447cb2e73b33cbd5edd5ae

**Comment by killajoe** [comment]
antergos-xfce-meta sig-errors too >> makes xfce install failing, not sure if there is something else... but this "signature errors are like an infection ;)

**Comment by karasu** [comment]
Thanks @killajoe . Fixed again.

There is something wrong in the build server (or that I make some mistake when instructing it to build packages). @lots0logs is the expert (in fact, he created the build server).

I'll be more cautious and test all packages myself before moving them to the antergos "stable" repository.
