### ISSUE TITLE
Package of v39 of GNOME dash-to-dock extension is buggy

### ISSUE THREAD

**Issue by ace214** [Antergos/antergos-packages#33]
Autohide was not working in the latest package of gnome-shell-extension-dash-to-dock (v39). 

When I rolled back to v38, it was fine, and when I installed v39 from the GNOME extensions website, it worked fine.

**Comment by dtschmitz** [comment]
If one goes to bugzilla for Gnome, there are several 'memory leak' trouble tickets open.  I find that I must restart gnome-shell or many extensions cease to function.  (alt-F2, r)

**Comment by lots0logs** [comment]
Issue was fixed upstream. Package rebuild triggered in 80a83c213ba7999e99fb1bcba01dcf380553501a
