### ISSUE TITLE
Couldn't install latest chrome-gnome-shell from extra repository

### ISSUE THREAD

**Issue by Noobsai** [Antergos/antergos-packages#330]
I try update chrome-gnome-shell package. [GNOME wiki](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Arch_Linux) says: 
Package is available in the official repositories: [chrome-gnome-shell](https://www.archlinux.org/packages/extra/any/chrome-gnome-shell/).
Current version in extra repository is 10.1-1, in the antergos repository: 9-1.
By defaults pacman and Package Manager ignore 10.1-1 from extra, and suggest to install 9-1 from antergos.
Temporary solution: specify repository - # pacman -S extra/chrome-gnome-shell

**Comment by killajoe** [comment]
https://github.com/Antergos/antergos-packages/commit/608f6a9a84272c7938bfa33ecfe4e02681652c2f
