### ISSUE TITLE
pamac / pacman conflict with pacman 5.1

### ISSUE THREAD

**Issue by ethanwu10** [Antergos/antergos-packages#332]
pamac has a dependency on `pacman>=5.0  pacman<5.1`, pacman 5.1.0-1 was released today causing dependency resolution errors and failed upgrade with `pacman -Syu` - to upgrade everything else, use `pacman -Syu --ignore=pacman`

**Comment by ethanwu10** [comment]
AUR pamac does not have `pacman<5.1` dependency (for 6.3.2), so I suppose it will work fine and just the dep needs to be updated...

**Comment by karasu** [comment]
Thanks for reporting this! We're working on this. I'll report here when it is done.

**Comment by lots0logs** [comment]
Fixed
