### ISSUE TITLE
Kalu is outdate

### ISSUE THREAD

**Issue by rplanchuelo** [Antergos/antergos-packages#336]
Kalu is outdate. The last version is 4.2 and it is 4.1 in Antergos.
antergos/kalu 4.1.0-1

 • [11:04:09] ~ » pacman -Ss kalu
antergos/kalu 4.1.0-1
    Upgrade notifier w/ AUR support, watched (AUR) packages, news

https://jjacky.com/kalu/

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/8ff0a07c53d306139a3e39f430b99e3a2eaaa0bd

Thanks!
