### ISSUE TITLE
python-xcpf Packaged Incorrectly

### ISSUE THREAD

**Issue by keeganmilsten** [Antergos/antergos-packages#340]
Hi there guys! I bet you didn't expect to see me here! Anyways, I was trying to build a Reborn ISO and I kept getting this error with the python-xcpf-2018-1-any.pkg.tar.xz package. 
```
error: failed retrieving file 'python-xcpf-2018-1-any.pkg.tar.xz' from mirrors.antergos.com : maximum file size exceeded
```

Apparently, this is supposed to be due to a package being packaged with an error in it. Here's a link to another group facing this problem, as well as the solution for them:
https://github.com/Alexpux/MSYS2-packages/issues/942

Hope this helps, and thank you so much!

**Comment by karasu** [comment]
This should fix it: https://github.com/Antergos/antergos-packages/commit/ddae1ef58732be6c92f8a532c16d25b8633b4807
Tell me if it's still not working for you.
Cheers!

**Comment by keeganmilsten** [comment]
Thank you so much @karasu! It worked like a charm, and all is right in my world once again. Hope to see you more this summer, and, as always, God bless.
