### ISSUE TITLE
aurman gives error for python

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#343]
`/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)`
aurman-git from AUR has version: 2.9.39.r1.gc7394d5-1 Antergos is on: 2.9.28-1

But AUR version giove me the same error here...

**Comment by karasu** [comment]
I'm in a hurry right now. I'll check this asap.

**Comment by sum01** [comment]
https://github.com/polygamma/aurman/issues/136 It's already fixed, just update aurman

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/39319f7c9ee58e1910a63b18ac9e53c782c3eb01
