### ISSUE TITLE
jetbrains-toolbox not work

### ISSUE THREAD

**Issue by Amosar** [Antergos/antergos-packages#344]
Hi, I have try to install jetbrains-toolbox with pacman but i'm not able to launch it
The `/home/amosar/.local/share/JetBrains/Toolbox/bin/` file exist but is empty.

![image](https://user-images.githubusercontent.com/14032531/41228301-3367d3f8-6d78-11e8-96e3-c1347089b28b.png)

**Comment by lots0logs** [comment]
Hi, you must use the .desktop launch file to start it.

**Comment by Amosar** [comment]
Yes but it not work too 
(it's the default .desktop that I have :/)
![image](https://user-images.githubusercontent.com/14032531/41367734-330ee80a-6f40-11e8-8317-bfc6132a31be.png)
![image](https://user-images.githubusercontent.com/14032531/41367764-45af9734-6f40-11e8-8cd4-183f2375ce0f.png)

**Comment by Amosar** [comment]
I think I have found the issue.
The `bin` file is empty in `/opt/JetBrains/Toolbox` 
And the `jetbrains-toolbox` executable is located on the `/opt/JetBrains/Toolbox` folder not on the `/opt/JetBrains/Toolbox/bin` folder

**Comment by lots0logs** [comment]
The first time you run it, the necessary files are created. I know it works because I use it myself. So long as you launch it from your applications menu and not the command line it should work.

**Comment by Amosar** [comment]
Okay this is weird. On my system it create the file but in the wrong place even if I run it from the applications menu
![image](https://user-images.githubusercontent.com/14032531/41421008-0f29a9a0-6ff6-11e8-9d46-af5da776382b.png)

**Comment by lots0logs** [comment]
Could you try uninstalling the package, removing `~/.local/share/JetBrains` and then reinstall the package and try to run it.
