### ISSUE TITLE
"Maximum File Size Exceeded" 

### ISSUE THREAD

**Issue by WorLord** [Antergos/antergos-packages#35]
I am unable to update Pamac as of today.  Every download attempt results in the "Maximum file size exceeded" error message.  What's worse, is that I do not recall installing Pamac, and even worse than that, Pamac appears to be an Antergos default (as other users on IRC and the Forums are reporting this blocking fresh installs).  

sudo pacman -Syy and sudo pacman -Syyu did not fix the issue.  

I was able to uninstall it and be on my way, but I'm not sure how I'd handle this on a fresh install.

**Comment by karasu** [comment]
Hi,
I can install/uninstall pamac here without any issues thanks to a lots.0.logs fix. Please, try it again and confirm that it's working for you.
Thanks!
