### ISSUE TITLE
cower depends on libalpm.so.10 but should be libalpm.so.11

### ISSUE THREAD

**Issue by HerrIrrtum** [Antergos/antergos-packages#352]
Please update cower
```
$ cower
  cower: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory

$ ldd /usr/bin/cower |grep libal
	libalpm.so.10 => not found
```
I.e. using aur/cower-git or (propably) aur/cower works as cower v.18 is pulled instead of antergos/cower v.17-1 .

This fixes pacaur as well.

**Comment by karasu** [comment]
Thanks! Fixed.
https://github.com/Antergos/antergos-packages/commit/2113382bc115bbd596067e610ef2e93c3f602bb2
