### ISSUE TITLE
Packages that are both in [community] and [antergos] 

### ISSUE THREAD

**Issue by pavlepiramida** [Antergos/antergos-packages#355]
Corebird is now in [community]

https://www.archlinux.org/packages/community/x86_64/corebird/

Should it also stay in Antergos?
Kinda redundant to have the two same packages in both repos.

**Comment by karasu** [comment]
@lots0logs I agree it should be removed.
https://github.com/Antergos/antergos-packages/commit/a0e6fde2ed2a9a35f7129b16c3312d20e3f5764e

**Comment by lots0logs** [comment]
Done.

**Comment by pavlepiramida** [comment]
adapta-gtk-theme also in [comm]
https://www.archlinux.org/packages/community/any/adapta-gtk-theme/
