### ISSUE TITLE
New Bulgarian Mirror

### ISSUE THREAD

**Issue by SlaSerX** [Antergos/antergos-packages#358]
Mirror domain name: mirrors.itbox.bg
Geographical location of the mirror: Bulgaria, Burgas
Supported access methods (http, ftp, rsync, ...): http, rsync
URLs for the above access methods: https://mirrors.itbox.bg/antergos , rsync://mirrors.itbox.bg
The name of the tier 1 mirror you are syncing from: rsync://mirror.de.leaseweb.net/antergos
An administrative contact email: office@itbox.bg

Bandwidth - Unlimited
Bandwidth Speed: 1gbit/s

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/da6cc4e0bee4ab2e2cdea9e7cece277cb706e9d4

Thanks!

@lots0logs can you add it to mirrors.antergos.com ?

**Comment by SlaSerX** [comment]
Thanks
