### ISSUE TITLE
vivaldi 1.15.1147.47-3 still not at the mirrors...

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#365]
https://build.antergos.com/package/vivaldi
seems build failed and stop getting builded again at the buildserver?

**Comment by killajoe** [comment]
@karasu @lots0logs  ?

**Comment by karasu** [comment]
@lots0logs is the vivaldi's package expert :grimacing:

**Comment by killajoe** [comment]
Is also not up to date anymore...
