### ISSUE TITLE
Numix Circle And Numix Square packages are outdated

### ISSUE THREAD

**Issue by palob** [Antergos/antergos-packages#366]
For packages ``numix-icon-theme-circle`` and ``numix-icon-theme-square`` Antergos lags behind 4 releases.

The Antergos repo comes with ``18.02.16`` while the latest upstream releases are ``18.08.01``.

https://github.com/numixproject/numix-icon-theme-circle/releases
https://github.com/numixproject/numix-icon-theme-square/releases

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/b8b439df5569b5f0355c6af6f8dd8d40ac7970aa

Thanks!

**Comment by palob** [comment]
Thank you.
