### ISSUE TITLE
Quazip Not updated to the latest version

### ISSUE THREAD

**Issue by DanitiKain** [Antergos/antergos-packages#373]
This causes issues with other packages specifically for me screencloud-git package and screencloud package itself.

https://aur.archlinux.org/packages/screencloud-git/#news

See comments section regarding quazip.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/82448d1c7f2b739cd020f4a850ba5b76a8ee43ea

Thanks for the warning!
