### ISSUE TITLE
SPL and current Kernel seem to fail on building modules

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#374]
https://github.com/Antergos/antergos-packages/tree/master/antergos/spl
https://forum.antergos.com/topic/10500/spl-install-failling

As i can read here: https://github.com/zfsonlinux/zfs/releases
it is may the problem that ZFS and SPL do not work with kernel bigger then 4.17, current is 4.18.3

This may also effect Installer (CNCHI) to fail on installing on ZFS, as it will buils modules against current kernel?

**Comment by killajoe** [comment]
my cnchi.log: https://ptpb.pw/nCZU

**Comment by killajoe** [comment]
cnchi do not stop finishing install .. but fails for sure on boot into system then...

![bildschirmfoto vom 2018-08-20 22-17-38](https://user-images.githubusercontent.com/16797647/44364343-fe327680-a4c6-11e8-88fd-de3f4a91b670.png)

**Comment by karasu** [comment]
https://github.com/zfsonlinux/zfs/pull/7792
https://github.com/zfsonlinux/zfs/issues/7785

**Comment by killajoe** [comment]
i do put the info to Announcements:

https://forum.antergos.com/topic/10509/current-zfs-do-not-work-with-current-kernel-4-18

**Comment by lots0logs** [comment]
This has been fixed
