### ISSUE TITLE
kdesudo // kdebase-runtime moved to AUR

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#377]
kdebase-runtime is moved to AUR also... so we may need to provide this on Antergos Repo to solve dependency for kdesudo ?

https://forum.antergos.com/topic/10533/kdesudo-depends-on-orphaned-package

https://forum.antergos.com/topic/10528/kde-installation-fails-on-localization-packages

**Comment by karasu** [comment]
Hi,

Latest kdesudo commit is three years old. As Arch is dropping all qt4 packages, I'm afraid we'll have to drop this one, too.

https://github.com/Antergos/antergos-packages/commit/d51701d15972a632020e231094db7b484994fb01

https://github.com/Antergos/Cnchi/commit/7b3f42cc16db55ad6b162d7056ff631a351a6168
Thanks for warning us 👌
