### ISSUE TITLE
Pamac on antergos repository is really outdated!

### ISSUE THREAD

**Issue by FredBezies** [Antergos/antergos-packages#399]
Hello.

I installed Cinnamon with antergos and I noticed that Pamac is really outdated. Current AUR version is 7.2.2... https://aur.archlinux.org/packages/pamac-aur

And Pamac 7.3.0rc is out. What about upgrading this package?

I was aware of this issue looking at pamac bugtracker: https://gitlab.manjaro.org/applications/pamac/issues/519

**Comment by lots0logs** [comment]
Note: Looks like they moved to Gitlab so we just need to update the release monitor attributes in PKGBUILD

**Comment by FredBezies** [comment]
> Note: Looks like they moved to Gitlab so we just need to update the release monitor attributes in PKGBUILD

Not only. You'll need to add git to depends and some little modifications also.

**Comment by lots0logs** [comment]
Obviously we're going to look at that as well. Also, I want to note that we do not push RC versions to our repos so the package is not actually "really outdated". Though it needs updating nevertheless.

**Comment by FredBezies** [comment]
Well... Just look at release history from gitlab repository.

Since pamac 6.4.0 ? There were:

1. 6.5.0 -> AUR support
2. 7.0.0 -> pamac cli and pamac-gui as fronted for libpamac
3. 7.1.0 -> mainly bugfixes
4. 7.2.0 -> support for AUR PKGBUILD modifications 

So, your pamac version is REALLY out of date.

https://gitlab.manjaro.org/applications/pamac/tags

And Pamac 7.3.0 is now out. So, you missed at least 5 main versions... It hurts.

https://gitlab.manjaro.org/applications/pamac/tags/v7.3.0

**Comment by killajoe** [comment]
pkgname=pamac-aur
pkgver=7.3.3

should we go with this or should we take pamac-classic? 
https://git.cromer.cl/cromer/pamac-classic

**Comment by lots0logs** [comment]
Fixed in https://github.com/Antergos/antergos-packages/commit/95aaa2677f64c7a1988485ae8b487b8224edd7e9

**Comment by posheylo** [comment]
It's again outdated, please need an update for the app.
