### ISSUE TITLE
vivaldi last update for 2018 

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#415]
2.2.1388.34 is out

https://vivaldi.com/blog/vivaldi-update-focus-on-details/

it says:
Better ‘Netflix’ support for Linux
This update brings a cheer for Linux fans. You can now watch Netflix, Prime Video, etc. as Vivaldi will now automatically fetch Widevine (Encrypted Media Extensions).

what does it mean for building?
As version from AUR still have **vivaldi-widevine (optional) – Widevine DRM Plugin** as dependency...

I do not get what wents wrong here on a first try to build:

`Usage: gen.py [options]
gen.py: error: no such option: --no-sysroot
Traceback (most recent call last):
  File "tools/gn/bootstrap/bootstrap.py", line 102, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools/gn/bootstrap/bootstrap.py", line 83, in main
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python2', '/home/joekamprad/Dokumente/GitHub/vivaldi/src/chromium-71.0.3578.85/tools/gn/build/gen.py', '--no-last-commit-position', '--out-path=/home/joekamprad/Dokumente/GitHub/vivaldi/src/chromium-71.0.3578.85/out/Release/gn_build', '--no-sysroot']' returned non-zero exit status 2
`

as it says: `gen.py: error: no such option: --no-sysroot `

what comes from `/vivaldi/src/chromium-71.0.3578.85/tools/gn/bootstrap/bootstrap.py`

**Comment by killajoe** [comment]
find a patch may working:
http://www.slackware.com/~alien/slackbuilds/chromium/build/patches/gn_bootstrap_remove_sysroot-options.patch

**Comment by killajoe** [comment]
https://chromium.googlesource.com/chromium/src/tools/gn/+/6630c2e334d7bc179e95a3d543a8eca3201d6725

https://chromium-review.googlesource.com/c/chromium/src/+/1333391

**Comment by killajoe** [comment]
i can build with aliens patch, including it directly looks a bit "hacky" to me so i just copy the patch into PKGBUILD dir ...

**Comment by killajoe** [comment]
with the patch it builds fine here!

**Comment by lots0logs** [comment]
Cool. Btw, I think we can just go ahead and remove widevine from our package since its no longer necessary.
