### ISSUE TITLE
Powerpill and pm2ml out of date

### ISSUE THREAD

**Issue by prolinko** [Antergos/antergos-packages#417]
Powerpill and its dependency pm2ml install python modules for version 3.6, so no longer works with python 3.7. Needs update.

**Comment by karasu** [comment]
Done!

https://github.com/Antergos/antergos-packages/commit/37d7ba1a21392b1bf567390bfa5b02d45532b608

https://github.com/Antergos/antergos-packages/commit/c43953c94d63865b842aabd80ab9d59bb15673fb
