### ISSUE TITLE
Octopi

### ISSUE THREAD

**Issue by prescott66** [Antergos/antergos-packages#42]
Can be builded Octopi in antergos repo? I know, it is in AUR but because of compilation against QT5 are broken tray icons.you can compile it against QT4 in your repo and make it working at least for Antergos users :-)

**Comment by karasu** [comment]
Download this tar file: https://aur.archlinux.org/packages/oc/octopi/octopi.tar.gz

Search this line in the PKGBUILD file:
`qmake-qt5 octopi-notifier.pro`
change it to:
`qmake-qt4 octopi-notifier.pro`
then run `makepkg -i`

Cheers!

P.S. We'll think about adding it...

**Comment by plumpudding** [comment]
+1 for adding it to the repo

**Comment by prescott66** [comment]
Still dont see octopi package in your repo

**Comment by karasu** [comment]
@prescott66 : I can see it. Maybe your mirror was not yet updated ¿?

**Comment by lots0logs** [comment]
@karasu I fired a rebuild of the package after reading his comment :wink:

**Comment by prescott66** [comment]
Checkmate ;-)
All is fine now

**Comment by karasu** [comment]
@lots0logs Thanks!
