### ISSUE TITLE
etcher is outdated

### ISSUE THREAD

**Issue by IsaakGroepT** [Antergos/antergos-packages#427]
in repo 1.4.4
upstream: 1.4.9

**Comment by scoronado12** [comment]
According to the AntBS, Etcher has not been updated since 2018-06-30

https://build.antergos.com/package/etcher

**Comment by killajoe** [comment]
https://github.com/Antergos/antergos-packages/pull/414

**Comment by killajoe** [comment]
https://github.com/Antergos/antergos-packages/pull/433

**Comment by killajoe** [comment]
```
aur/etcher 1.5.5-2 (+164 5.43%) (Installed: 1.4.9-1)
    Burn images to SD cards & USB drives, safe & easy
antergos/etcher 1.4.4-3 (57.0 MiB 209.6 MiB) (Installed: 1.4.9-1)
    Burn images to SD cards & USB drives, safe & easy
```
still not updated on the mirrors

**Comment by killajoe** [comment]
antergos/etcher 1.5.5-1 (45.0 MiB 217.8 MiB) (Installed: 1.5.5-2)

**Comment by karasu** [comment]
Thanks!
