### ISSUE TITLE
gnome-mpv is hugely outdated 2017 version

### ISSUE THREAD

**Issue by IevgenSobko** [Antergos/antergos-packages#428]
Seems you are using the version that was released in 2017.
If you aren't going to support it better to fall back to arch version that is updated and remove it from antergos repository

**Comment by killajoe** [comment]
`antergos/gnome-mpv 0.13-1 
    A simple GTK+ frontend for mpv.    
community/gnome-mpv 0.15-1 
    Simple GTK+ frontend for mpv `

is in archlinux community since 2018-04-18 no need to packaging this on antergos repo.

**Comment by killajoe** [comment]
```
community/gnome-mpv 0.16-1 (134.6 KiB 551.0 KiB) (Installed: 0.15-1)
    Simple GTK+ frontend for mpv
antergos/gnome-mpv 0.13-1 (129.0 KiB 742.0 KiB) (Installed: 0.15-1)
    A simple GTK+ frontend for mpv.
```
still no update on this...

**Comment by killajoe** [comment]
removed from Antergos repo, now available over community

**Comment by killajoe** [comment]
@IevgenSobko can you close this please!

**Comment by IevgenSobko** [comment]
Today got the update from community channel gnome-mpv 0.16
