### ISSUE TITLE
No wifi once installed

### ISSUE THREAD

**Issue by matthieu526** [Antergos/antergos-packages#43]
Hello,

I installed AntergOS for the second time on a second computer and I have the same issue. The wifi works fine when I use the liveCD, but once it is installed I don't get to connect anymore. I can't even choose or see the differents networks. I installed it with cinnamon.

Thanks in advance,

Matthieu526

**Comment by karasu** [comment]
@matthieu526 : This is not the place for this issue. You're posting in antergos-packages and this is not package related but setup related.

Please, post this in our forum: http://forum.antergos.com (and tell us which device are you using in your post).

Thanks!
