### ISSUE TITLE
Packages for numix-icon-theme-* are outdated.

### ISSUE THREAD

**Issue by palob** [Antergos/antergos-packages#432]
https://github.com/numixproject/numix-icon-theme-circle/releases
https://github.com/numixproject/numix-icon-theme-square/releases

**Comment by killajoe** [comment]
https://github.com/Antergos/antergos-packages/pull/434/commits/23c9fc2ae25590a5cfce7bee7161b181eb74a94e

**Comment by palob** [comment]
Updated in #434.
