### ISSUE TITLE
mate-mint-menu dependency moved to AUR: python2-keybinder2

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#437]
mate install fails caused by mate-mint-menu needs a dependency no longer available as a package from mirrors:

[cnchi.log](https://privatebin.net/?b7ce59a997eed8a3#adE31z+YLvnq8b+J57ZywLZV+uAGD7MhffJd3xfqkPQ=)

related post on Antergos Forum:

https://forum.antergos.com/topic/11494/antergos-mate-installation-broken/3

**Comment by karasu** [comment]
@lots0logs should we add this package (python2-keybinder2) to our repo?

**Comment by killajoe** [comment]
may updating mate-mint-menu as [mintmenu](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mintmenu) from AUR do not have ita s a dep?

**Comment by killajoe** [comment]
mate-mint-menu on Antergos is: pkgver=5.7.0alpha2

**Comment by bryce-lynch** [comment]
I wanted to install MATE today and had the same issue (missing package, installation stopped).

**Comment by bryce-lynch** [comment]
I wanted to install MATE today (from current live ISO) and had the same issue (missing package, installation stopped).

**Comment by killajoe** [comment]
as it looks like it is changed to brisk-menu, but configs ere not changed to remove mate-mint-menu from panel and adding brisk-menu ..

**Comment by lots0logs** [comment]
mate menu is still available and has been updated so installs should no longer fail.
