### ISSUE TITLE
Packages that should be removed from Antergos since they are well updated in upstream

### ISSUE THREAD

**Issue by manuel-192** [Antergos/antergos-packages#440]
atril
mate-calc
mate-icon-theme
xed
yad (exists in repos!)

Most if not all of them are outdated in Antergos.

**Comment by karasu** [comment]
@lots0logs should we drop those packages?

**Comment by manuel-192** [comment]
Actually yad is not upstream but from AUR. An outdated yad package is in the Antergos repos, but it is not in the Antergos list https://github.com/Antergos/antergos-packages/tree/master/antergos.

**Comment by manuel-192** [comment]
Thanks for resolving the other listed packages.

In **https://repo.antergos.info/antergos/x86_64** there still is an outdated **yad** package. That package should be removed from the repo, since it blocks the usage of the same AUR package.

Have I understood correctly that this repo is the "master" repo from where other repos copy their stuff? If not, is there such a master repo?

**Comment by karasu** [comment]
@manuel-192 I'll try to update yad when I get home (I'm at work atm).

>Have I understood correctly that this repo is the "master" repo from where other repos copy their stuff? If not, what is the master repo?

Yes, you're right, this is the master repo.

**Comment by manuel-192** [comment]
Thanks. As yad is not currently in https://github.com/Antergos/antergos-packages/tree/master/antergos but a package exists in the https://repo.antergos.info/antergos/x86_64, do you plan to create a new yad package for Antergos, or simply update the repo package? I have no preferences here, just asking.
