### ISSUE TITLE
Remove outdated Vivaldi package

### ISSUE THREAD

**Issue by hordosikrisztian** [Antergos/antergos-packages#442]
Please remove the outdated and orphan Vivaldi package from the antergos repo, because it has a conflict with the AUR one, which is always up-to-date.

Pamac should also be able to see the vivaldi package from the AUR.

**Comment by killajoe** [comment]
simple naming is the issue here, as both have the same name...

**Comment by killajoe** [comment]
But you are right if there is no way to keep packages up to date they should be removed, or moved to second antergos repo like antergos-extra, so you will be able to simple remove this from pacman.conf 
but keeping antergos base on the list...
