### ISSUE TITLE
Forum broken

### ISSUE THREAD

**Issue by xstable** [Antergos/antergos-packages#443]
Don't know where to report this, that's why I choose this issue-tracker.
It isn't possible to login in the Forum: https://forum.antergos.com/

If I click on Login, and enter my credentials, I'm redirected to the dashboard-page of the forum. But on upper right corner, there is still "Login"-Button.

Even if I click on Search-Field, I got a notice, that I only can use it if I've logged in.
Do I click again on Login, It redirect me to login-page... and after 3 seconds back to the Dashboard-Page (still not logged in).

In the Browser-Console, you see error like: 
```
Uncaught TypeError: app.replaceSelfLinks is not a function
    at processHtml ((index):1887)
    at onLoad ((index):1846)
```
...for both Firefox and Chrome (at Linux)

Please Fix this.

**Comment by suther** [comment]
Can be closed. Work now.
