### ISSUE TITLE
qt5-styleplugins has been removed from the [community] repository

### ISSUE THREAD

**Issue by MaxXor** [Antergos/antergos-packages#450]
It's still a dependency of `antergos-common-meta`.

**Comment by bonh** [comment]
And I think this breaks the installer

**Comment by joaoflf** [comment]
Anyway of circumventing the error in the installer?

**Comment by killajoe** [comment]
all installs are failing at the moment as long as this is not solved....

**Comment by killajoe** [comment]
@lots0logs :
https://forum.antergos.com/topic/11556/antergos-common-meta-changes-kde-app-fonts/ 

may problematic to add **qt5ct** package to this? as it will override fontsettings inside KDE sessions?
