### ISSUE TITLE
When we resume after suspend, the mouse wheel response becomes very slow

### ISSUE THREAD

**Issue by manjulaksh** [Antergos/antergos-packages#466]
When I suspend the system and later resume, the mouse wheel response becomes extremely slow. It doesn't get better after that. I have to unplug the mouse's USB plug and plug it again to make it work properly.

OS: Antergos 
Kernel: x86_64 Linux 5.0.6-arch1-1-ARCH
Packages: 922
Shell: bash 5.0.2
Resolution: 3286x1080
DE: KDE 5.56.0 / Plasma 5.15.4
WM: KWin
GTK Theme: Numix-Frost-Light [GTK2/3]
Icon Theme: Numix
Font: Noto Sans Regular
CPU: Intel Core i3 M 350 @ 4x 2.266GHz [49.0°C]
GPU: intel
RAM: 1781MiB / 5757MiB

**Comment by lots0logs** [comment]
This is an issue with the driver in the linux kernel. There is a workaround though. Create the following file and make it executable:

`/usr/lib/systemd/system-sleep/fix-mouse-wheel.sh`:
```bash
#!/bin/bash

if [[ pre = "${1}" ]]; then
	for mod in hid_logitech_hidpp hid_logitech_dj usbhid
	do
		sudo rmmod $mod
	done
else
   	for mod in hid_logitech_hidpp hid_logitech_dj usbhid
	do
		sudo modprobe $mod
	done
fi
```
