### ISSUE TITLE
Lock button in gnome-shell-extension-status-menu-buttons doesn't lock screen

### ISSUE THREAD

**Issue by JPLeBreton** [Antergos/antergos-packages#50]
I press the button and it doesn't do anything.  Possibly related to issue #31.  I installed gnome-shell-extension-lockscreen-lightdm because it does work, but it gets replaced by gnome-shell-extension-status-menu-buttons every time any update downloads, so I don't bother now.

**Comment by lots0logs** [comment]
Could you post your journal log after attempting to lock the screen a few times? Thanks!

**Comment by JPLeBreton** [comment]
I'd be happy to, what do you mean by journal and how would I get at that data?

**Comment by lots0logs** [comment]
http://forum.antergos.com/topic/1885/how-to-include-system-logs-when-asking-for-help

**Comment by JPLeBreton** [comment]
While troubleshooting another issue that stemmed from not having an Xorg config file, this issue seems to have resolved itself, feel free to close it.

**Comment by FernandoVelcic** [comment]
I have same issue in gnome3 antergos, lock screen button not working

**Comment by ManuGithubSteam** [comment]
Mee too. But i doubt its an antergos problem...
