### ISSUE TITLE
The topicon extension is broken in Gnome Shell 3.17.90

### ISSUE THREAD

**Issue by davidgumberg** [Antergos/antergos-packages#61]
I will add screenshots and more specific bug details tomorrow.

**Comment by lots0logs** [comment]
This should be resolved with the latest update. Please let us know if that's not the case. Thanks.

**Comment by ashtipliyski** [comment]
I managed to find the 28-3 version in AUR but when I do an update with pacman the 27-1 from the antergos repo downgrades the package. The 27-1 version seems to have an issue with the size of the icons used and how they are scaled. 

Screenshots from the different version of the package:

27-1 (antergos)
![screenshot from 2016-02-04 12-22-22](https://cloud.githubusercontent.com/assets/13658658/12814860/368cacbc-cb3a-11e5-8078-0be552bb9306.png)

28-3 (AUR)
![screenshot from 2016-02-04 12-23-28](https://cloud.githubusercontent.com/assets/13658658/12814867/4174317c-cb3a-11e5-9941-254c1c0695f1.png)
