### ISSUE TITLE
broadcom-wl -> dkms

### ISSUE THREAD

**Issue by lots0logs** [Antergos/antergos-packages#63]
Reminding myself to look into the possibility of packaging `broadcom-wl` in a way that it doesn't require a rebuild with every new kernel update.

**Comment by Yoshi2889** [comment]
Looking at the broadcom-wl package, this seems incorporated now

**Comment by karasu** [comment]
Nope, I don't think so. Thanks!

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/6914/broadcom-bcm43142-chip-wireless-driver-problem
I do not know the reason but here two users needs to take the version from AUR to make there devices work.
