### ISSUE TITLE
Plymouth crashes: invalid opcode 

### ISSUE THREAD

**Issue by ial0** [Antergos/antergos-packages#64]
After trying out plymouth I get this error,

traps: plymouthd[195] trap invalid opcode ip:7fa80c3f85d2 sp:7ffe0f9fd7b0 error:0 in libply.so.4.0.0[7fa80c3ea000+17000]

I don't have this problem when building plymouth from the AUR.

**Comment by ial0** [comment]
I have just built the package from this repository. Firstly the md5sums were not updated when antergos.zip was modified.  After fixing this (see #65 ) I now have a working Antergos splash. It looks like it just needs a rebuild.

**Comment by lots0logs** [comment]
@ial0 The checksums are generated automatically at the time of building the package. I'll go ahead and fire a rebuild just in case there was an error with the previous build, Cheers!
