### ISSUE TITLE
antergos-mirrorlist - russia

### ISSUE THREAD

**Issue by voynovia** [Antergos/antergos-packages#66]
Add server please:

# Russia
Server = http://mirror.yandex.ru/mirrors/cinnarch/$repo/$arch

**Comment by lots0logs** [comment]
Hi, if you could, please review the [New Mirror Guidlines](https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/) and confirm that you have configured your mirror correctly. Also, be sure to provide us with an administrative contact email. Thanks!

**Comment by varlesh** [comment]
Please add russian mirror to package *antergos-mirrorlist*:
```
# Russia
Server = http://mirror.yandex.ru/mirrors/cinnarch/$repo/$arch
```
Descripton:
Welcome to Yandex Linux mirror, hosted at Yandex, Russian Federation.
My hostname is node03h.mirror.yandex.net
Contacts: opensource@yandex-team.ru
We support http, ftp and rsync protocols.

**Comment by Doaxan** [comment]
I also would like to the mirror was added.

**Comment by varlesh** [comment]
thx :+1:

**Comment by faidoc** [comment]
Server also included in our mirror georedirector. Thanks
