### ISSUE TITLE
errors on upgrade of antergos-kde-setup to 0.1.6

### ISSUE THREAD

**Issue by blizzz** [Antergos/antergos-packages#69]
Upgrading to antergos-kde-setup-0.1.6-1-any  left this messages in the log:

```
upgrading antergos-kde-setup 
Setting Antergos KDE setup to user /root
cp: failed to access '/home//root': No such file or directory 
chown: invalid user: '/root:users'
error: command failed to execute correctly 
```

No idea whether it's really problematic, but it does not seem right ;)

**Comment by karasu** [comment]
Wow, I totally missed this one. @lots0logs did you fixed this one?

**Comment by blizzz** [comment]
I think it is fixed meanwhile, closing.
