### ISSUE TITLE
zfs does not install correctly

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-packages#73]
I get this message when installing (pacman -S zfs)
I'll check it when I have the time.

```
Error! Invalid number of arguments passed.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
Error! Invalid number of arguments passed.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
```

**Comment by lots0logs** [comment]
@karasu I fixed this (well I thought I had) but you later un-did my changes and put it back the way it was (so I assumed that they didnt work) :laughing:  I'm glad you noticed this before I cut the January ISOs!

**Comment by karasu** [comment]
Sorry!!! But it wasn't working for me, that's why I tried to fix it
(without success)

El dilluns, 18 de gener de 2016, Dustin Falgout <notifications@github.com>
va escriure:

> @karasu <https://github.com/karasu> I fixed this (well I thought I had)
> but you later un-did my changes and put it back the way it was (so I
> assumed that they didnt work) [image: :laughing:] I'm glad you noticed
> this before I cut the January ISOs!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/antergos-packages/issues/73#issuecomment-172645008>
> .
>


-- 
Enviat amb el meu Iphone

**Comment by X4** [comment]
Important: dkms builds will fail for `zfs-0.6.5.5.r2063_4.4.5_1-1` and `spl-0.6.5.5.r969_4.5.1_1-1`
You've already pushed these updates upstream. People installing the zfs/spl update will not be able to boot again and see this error when the DKMS Hook triggers. 

```
checking spl source directory... /usr/src/spl-0.6.5.5.r2063_4.4.5_1
configure: error:
	*** Please make sure the kmod spl devel package for your distribution
	*** is installed then try again.  If that fails you can specify the
	*** location of the spl source with the '--with-spl=PATH' option.
	*** The spl version must match the version of ZFS you are building,
	*** 0.6.5.  Failed to find spl.release.in in the following:
	300,

Building module:
cleaning build area...(bad exit status: 2)
make KERNELRELEASE=4.4.5-1-ARCH...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.5-1-ARCH (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.5.r2063_4.4.5_1/build/make.log for more information.
```
After an hour or so I noticed that the paths passed to ./configure don't actually exist! 
Then I checked `/usr/src/zfs-0.6.5.5.r2063_4.4.5_1/dkms.conf` and replaced
`PACKAGE_VERSION="0.6.5.5.r2063_4.4.5_1"`
with
`PACKAGE_VERSION="0.6.5.5.r969_4.5.1_1"`

And `dkms install -m zfs -v 0.6.5.5.r2063_4.4.5_1 -k 4.4.5-1-ARCH` has built the module successfully. Now I just need to run mkinitcpio -P and I'm set.

**Comment by karasu** [comment]
I can confirm this. Spl does not build as it is

El dimecres, 16 de març de 2016, X4 <notifications@github.com> va escriure:

> Important: dkms builds will fail for zfs-0.6.5.5.r2063_4.4.5_1-1 and
> spl-0.6.5.5.r969_4.5.1_1-1
> You've already pushed these updates upstream. People installing the
> zfs/spl update will not be able to boot again and see this error when the
> DKMS Hook triggers.
>
> checking spl source directory... /usr/src/spl-0.6.5.5.r2063_4.4.5_1
> configure: error:
>     *** Please make sure the kmod spl devel package for your distribution
>     *** is installed then try again.  If that fails you can specify the
>     *** location of the spl source with the '--with-spl=PATH' option.
>     *** The spl version must match the version of ZFS you are building,
>     *** 0.6.5.  Failed to find spl.release.in in the following:
>     300,
>
> Building module:
> cleaning build area...(bad exit status: 2)
> make KERNELRELEASE=4.4.5-1-ARCH...(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.4.5-1-ARCH (x86_64)
> Consult /var/lib/dkms/zfs/0.6.5.5.r2063_4.4.5_1/build/make.log for more information.
>
> After an hour or so I noticed that the paths passed to ./configure don't
> actually exist!
> Then I checked /usr/src/zfs-0.6.5.5.r2063_4.4.5_1/dkms.conf and replaced
> PACKAGE_VERSION="0.6.5.5.r2063_4.4.5_1"
> with
> PACKAGE_VERSION="0.6.5.5.r969_4.5.1_1"
>
> And dkms install -m zfs -v 0.6.5.5.r2063_4.4.5_1 -k 4.4.5-1-ARCH has
> built the module successfully. Now I just need to run mkinitcpio -P and I'm
> set.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/antergos-packages/issues/73#issuecomment-197160178>
>


-- 
Enviat amb el meu Iphone

**Comment by lots0logs** [comment]
@karasu I'm looking into it now...

**Comment by karasu** [comment]
@lots0logs sorry, I meant zfs. spl is still at r969 ¿?

**Comment by lots0logs** [comment]
@karasu It should be fine now. It works for me. If you arent pulling directly from the build server then you need to wait for the mirrors to sync.

**Comment by karasu** [comment]
OK. I'll check it. Thanks!

**Comment by X4** [comment]
maybe it would be now necessary to check if people have the previous zfs and split build. Because just updating zfs would still error due to wrong paths. Easy fix. Remove zfs and spl then reinstall the latest.

**Comment by X4** [comment]
The packagr version naming is confusing. Why not simply use 0.6.5.5 for both? You could then simplify to ’dkms install -m zfs -v $ZFS_VERSION -k $(uname -r)’

**Comment by X4** [comment]
yeahhh now zfs or zpool list etc work properly and don't throw Illegal Instruction!

**Comment by lots0logs** [comment]
> The package version naming is confusing. Why not simply use 0.6.5.5 for both? You could then simplify to ’dkms install -m zfs -v $ZFS_VERSION -k $(uname -r)’

The version is like that to properly track the package since zfs and the kernel do not operate on the same release schedule. Though the package version has nothing to do with the kernel modules when built by dkms as it uses only the zfs version. You can see it for yourself in `/usr/src`. :smile: Cheers!

**Comment by karasu** [comment]
Yep, I can confirm it's working now.
