### ISSUE TITLE
Missing libalpm.so on yaourt (package-query)

### ISSUE THREAD

**Issue by Akonovo** [Antergos/antergos-packages#76]
Seems that there is something buggy in package-query build.
Since the last pacman update, yaourt stopped working because it cant find libalpm.so library. Few people are posting in Antergos forums about this issue.

Ive found that package-query had its latest update today (https://aur.archlinux.org/packages/package-query/) while in Antergos repositories last update was in december.
Both repositories share the same version number (1.7-2). However ive installed aur version and the issue was fixed.

So I think that a build/upgrade is needed on that package to let Yaourt work again

**Comment by rushsteve1** [comment]
I had the same issue earlier today, but it was fixed with a simple ```pacman -Syu```

**Comment by Akonovo** [comment]
Nice to hear! but unfortunatelly In my case pacman -Syyu didnt fixed it. Even uninstalling yaourt and package-query and then installing them again.. As long as the update comes from Antergos Repositories I get libalpm.so missing error in yaourt. The only way I could fix it through pacman was disabling antergos and enabling archlinuxfr repositories (http://repo.archlinux.fr/$arch) that seems to have the latest version of package-query.

Also, there are people here http://forum.antergos.com/topic/3826/new-pamac-not-starting/15 reporting libalpm.so issues with pamac but I coudnt confirm that issue

**Comment by Akonovo** [comment]
Repository updated and fixed!
