### ISSUE TITLE
Jockey not in actual repos and unresolved dependencies 

### ISSUE THREAD

**Issue by rushsteve1** [Antergos/antergos-packages#77]
The package for Jockey is here, but not in the current Antergos repos. This is a minor issue, but when you attempt to install it using the PKGBUILD file it is impossible to download the python2-xkit package, as it is not in the Arch, or Antergos repos or the AUR. As someone who has spent the last 2 days trying to get a driver to work, Jockey would be a welcome help.

**Comment by lots0logs** [comment]
Jockey doesn't work on Arch. Its an Ubuntu app that relies heavily on ubuntu/debian packaging. There was some work done on porting the application to Arch/Antergos but it turned out to be more trouble than it was worth. Sorry for the confusion.
