### ISSUE TITLE
[Suggestion] Add spotify package

### ISSUE THREAD

**Issue by artur9010** [Antergos/antergos-packages#80]
https://aur.archlinux.org/packages/spotify/

**Comment by Yoshi2889** [comment]
Agreed.

**Comment by karasu** [comment]
Hi,

Spotify is buggy software in linux (to say the least). I know it's a wide used software but I'm sure maintaining this is going to be a nightmare (check all comments in AUR, it seems each day a new issue appears).

Oh, and the app isn't compiled when installed (in fact, it installs an already compiled binary), so adding it to our repo won't add any benefits to our users.
