### ISSUE TITLE
gnome-shell-extension-status-menu-buttons - Buttons Disappear, Extension Crash

### ISSUE THREAD

**Issue by mykrobinson** [Antergos/antergos-packages#82]
When using GDM, after a short time, the power/suspend/hibernate buttons disappear from the Gnome Shell status menu.

I know that the extension clearly says that it is for use with LightDM, however, other users are stating that the extension works fine for them even with GDM enabled. When the problem occurs, if I restart Gnome with Alt+F2 and r, the buttons come back, but the extension crashes again within a few minutes. If I open the tweak tool when this happens, the extension shows as turned off and in an error state, unable to be turned back on.

Here's a screenshot of what happens:

http://imgur.com/dG18TG7

I have enabled another extension (suspend button) instead since it seems to keep the buttons intact, but am very curious to figure out what this isn't working right.

**Comment by lots0logs** [comment]
Hi, If you could please post your issue to Antergos/gnome-shell-extension-status-menu-buttons repo and include a [paste2](http://paste2.org) link for your journal log output immediately following an occurrence of the issue. Thanks!
