### ISSUE TITLE
Terminix package issues

### ISSUE THREAD

**Issue by gnunn1** [Antergos/antergos-packages#83]
I'm the developer of terminix and I have a user reporting an issue (https://github.com/gnunn1/terminix/issues/125) with the antergos package for terminix. Looking at the package, it appears you are shipping an out-dated copy of com.gexperts.Terminix.gschema.xml for some reason?

Please use the com.gexperts.Terminix.gschema.xml that is included in the release package instead of adding your own, this way it will always be up to date.

**Comment by dsboger** [comment]
Just a heads up for new changes in the schema.
