### ISSUE TITLE
Firefox-beta is broken now

### ISSUE THREAD

**Issue by Yoshi2889** [Antergos/antergos-packages#86]
```
~ » firefox-beta
XPCOMGlueLoad error for file /opt/firefox-beta-46.0b1/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

I have gtk3 installed. The AUR package firefox-beta-bin works fine.

**Comment by Danysan1** [comment]
I have the same problem.
Trying to solve the problem I installed `lib32-gtk3` from multilib and the output changed to:
```
XPCOMGlueLoad error for file /opt/firefox-beta-46.0b1/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
So it looks like the package wants the 32-bit version (really strange). 
`dbus-glib` does not have a multilib version so I can't test if it would work with a 32bit version.

**Comment by Yoshi2889** [comment]
Is this still an issue?
