### ISSUE TITLE
CopyQ does not work

### ISSUE THREAD

**Issue by marmotz** [Antergos/antergos-packages#88]
core dump with antergos version.
I must install AUR (v2.5.0) to have a working version of CopyQ :-/

**Comment by marmotz** [comment]
$ copyq
[1]    17068 illegal hardware instruction (core dumped)  copyq

[coredump.zip](https://github.com/Antergos/antergos-packages/files/180546/coredump.zip)

**Comment by marmotz** [comment]
```
$ coredumpctl info 17068
           PID: 17068 (copyq)
           UID: 1000 (marmotz)
           GID: 100 (users)
        Signal: 4 (ILL)
     Timestamp: sam. 2016-03-19 00:33:20 CET (19min ago)
  Command Line: copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (marmotz)
       Boot ID: 7bc85b945d1e4e74bd388f906e66d39b
    Machine ID: dea42d19b1b9458ebebb90fea05ba1dc
      Hostname: xiha
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.7bc85b945d1e4e74bd388f906e66d39b.17068.1458344000000000000000.lz4
       Message: Process 17068 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 17068:
                #0  0x000000000046aed4 n/a (copyq)
                #1  0x000000000046e220 _ZN15ClipboardServerC1ERiPPcRK7QString (copyq)
                #2  0x00000000004673e6 main (copyq)
                #3  0x00007fc6c4d3d710 __libc_start_main (libc.so.6)
                #4  0x00000000004676a9 _start (copyq)
                
                Stack trace of thread 17069:
                #0  0x00007fc6c4dfbc3d poll (libc.so.6)
                #1  0x00007fc6c38c2ae2 n/a (libxcb.so.1)
                #2  0x00007fc6c38c4757 xcb_wait_for_event (libxcb.so.1)
                #3  0x00007fc6bdf480a9 n/a (libQt5XcbQpa.so.5)
                #4  0x00007fc6c56fb9ae n/a (libQt5Core.so.5)
                #5  0x00007fc6c4b07424 start_thread (libpthread.so.0)
                #6  0x00007fc6c4e04cbd __clone (libc.so.6)
```

**Comment by lots0logs** [comment]
It works fine for me. I don't think it is a packaging issue. I recommend reporting the issue to the developer : https://github.com/hluk/CopyQ/issues

**Comment by marmotz** [comment]
@lots0logs For test, i've just installed CopyQ from AUR, but i've edited PKGBUILD. I updated version number to 2.6.0... and it's working.

So if my manual update from AUR is working, it seems that this repo has an error somewhere...

**Comment by lots0logs** [comment]
@marmotz Hmmm..I think I might know the problem. I will rebuild the package here shortly. Please let me know if the new package has the same issue.

**Comment by marmotz** [comment]
@lots0logs thanks !!
2.6.1-2 works perfectly :)

What is libxtst ?

**Comment by lots0logs** [comment]
Okay, good. I'm glad its resolved for you :)



> What is libxtst ?

That's a testing library for X (xorg). I didn't have anything to do with this issue though. I just noticed that it was duplicated in the depends array so I removed the duplicate :wink:

**Comment by marmotz** [comment]
What was the problem?

**Comment by lots0logs** [comment]
antergos/antbs#3
