### ISSUE TITLE
libreoffice-installer should be deleted

### ISSUE THREAD

**Issue by Wyn10** [Antergos/antergos-packages#89]
Libreoffice is a feature in the installer.  If the user wants it they would choose it there - If they don't want it we shouldn't be giving it to them in any form.

https://github.com/Antergos/Cnchi/pull/567

**Comment by SalahAdDin** [comment]
Guys!

**Comment by karasu** [comment]
It was already removed from Cnchi a long time ago (https://github.com/Antergos/Cnchi/commit/e8fca47ca80c24ce4cd9c1240f6f3b8c4f69b440)
And I cannot find the package in here either.
Closing.
