### ISSUE TITLE
n1-package broken depend

### ISSUE THREAD

**Issue by varlesh** [Antergos/antergos-packages#93]
Nylas N1 not working without gnome-keyring.
LOG:
`Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files`
Please add **gnome-keyring** to depend.

**Comment by manjarqo** [comment]
confirm this issue

**Comment by karasu** [comment]
Added as an optional dependency, as it could be another implementation of org.freedesktop.secrets
