### ISSUE TITLE
lightdm-webkit2-greeter fails to install due to updated dependencies

### ISSUE THREAD

**Issue by Wyn10** [Antergos/antergos-packages#94]
webkit2gtk and gtk3 were both updated yesterday to 2.12.0-2 and 3.20.2-1. Greeter is now looking for older packages.

https://www.archlinux.org/packages/extra/x86_64/webkit2gtk/
https://www.archlinux.org/packages/extra/x86_64/gtk3/

**Comment by karasu** [comment]
@lots0logs Have you seen this?

I do not get it, as the PKGBUILD shows

`depends=('lightdm' 'webkit2gtk>=2.10.8' 'gtk3>=3.18')`

**Comment by Wyn10** [comment]
Up to 2 people now and light-locker is now being reported with the same issue.

**Comment by karasu** [comment]
@lots0logs The PKGBUILD is ok, only that the package it's still in staging. Did you keep it there for some reason?

**Comment by varlesh** [comment]
I confirm this!

**Comment by Wyn10** [comment]
https://forum.antergos.com/topic/4263/impossible-update-for-dependencies-issues-with-lightdm-webkit2-greeter/2

**Comment by dtschmitz** [comment]
This is a dumb-ass error.  Fix it please.

**Comment by varlesh** [comment]
Many users can not install system, because Cnchi  fails. I know this Archlinux problem, because ligtdm available on arch repo. BUT HOW INSTALL ANTERGOS WITH DE?
![photo_2016-04-09_20-15-22](https://cloud.githubusercontent.com/assets/8083855/14405114/e137e748-fe8f-11e5-914f-e43d273aadd7.jpg)

**Comment by Doaxan** [comment]
Confirm this.

**Comment by tuxayo** [comment]
@varlesh  @Doaxan and people in the future.

We can now add thumbs ups to the issue directly as a clean way to confirm it.
![capture d ecran_2016-04-09_19-30-10](https://cloud.githubusercontent.com/assets/2678215/14405197/9055f9ce-fe89-11e5-8c75-67bf32d7692a.png)

**Comment by varlesh** [comment]
@lots0logs Please move package to stable, because Cnchi fails. Users can not install OS and can not update system!!!

**Comment by Wyn10** [comment]
python-gobject is also being reported.

**Comment by SunDwarf** [comment]
This has been broken for weeks...?

**Comment by Wyn10** [comment]
@SunDwarf This bug only started today.

**Comment by czbaker** [comment]
So, I am having the same problem, I did an update and just `--ignore`d the broken stuff, and now my system boots to a black screen with a cursor, but GNOME never shows up.

I guess that was a bad idea, haha.  I didn't think anything like that would happen.  Oh well.

**Comment by SunDwarf** [comment]
Nope, I've had issues with upgrades since at least last week.

**Comment by Wyn10** [comment]
@karasu Updated packages.  Expect few hours for mirrors to sync.

@SunDwarf The packages listed above were updated **_today_**.  Whatever issue you have is not regarding this one, this is only another issue.  Instead of strictly complaining post your issue on the [Antergos forums](https://forum.antergos.com/) or post a bug report in the repo with what it's regarding.  You have not posted anything regarding a problem that I can find.

**Comment by varlesh** [comment]
lightdm-webkit-greeter from staging repo not working. Show empty space only - no login, no password, no session.
Temp solution - use other DM - remove Lightdm and install SDDM (KDE) or GDM (GTK).

**Comment by FinlStrm** [comment]
Yep... Also effecting me.... -sadface-

```
[root@Reaper Downloads]# pacman -Syyu
:: Synchronizing package databases...
 core                                                                                         121.1 KiB  1808K/s 00:00 [########################################################################] 100%
 extra                                                                                       1744.5 KiB  3.26M/s 00:01 [########################################################################] 100%
 community                                                                                      3.4 MiB  6.82M/s 00:01 [########################################################################] 100%
 multilib                                                                                     161.1 KiB  2.16M/s 00:00 [########################################################################] 100%
 antergos                                                                                     252.6 KiB  1684K/s 00:00 [########################################################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: lightdm-webkit2-greeter: installing webkit2gtk (2.12.0-2) breaks dependency 'webkit2gtk<2.12'
:: lightdm-webkit2-greeter: installing gtk3 (3.20.2-1) breaks dependency 'gtk3<3.20'
```

**Comment by voyeg3r** [comment]
I already had some problems with lightdm and have installed GDM instead  
The only trick is: Don't forget to run this command: 

    sudo systemctl enable gdm.service -f

My update is running ok

**Comment by varlesh** [comment]
For KDE users temporary solution:
```
sudo pacman -R lightdm lightdm-webkit2-greeter
sudo pacman -S sddm sddm-kcm
sudo systemctl enable sddm.service -f
```

**Comment by lots0logs** [comment]
There is no need for temporary solutions. All that is needed is a little bit of patience. Just because pacman tells you that updates are available doesn't mean you must install them at that very moment. Sit back, relax, and you will see this "issue" disappear as quickly as it appeared.

**Comment by varlesh** [comment]
@lots0logs Yes we must wait. But how other user who could not install OS, because Cnchi fails. See msg https://github.com/Antergos/antergos-packages/issues/94#issuecomment-207818982

**Comment by lots0logs** [comment]
@varlesh They too must wait. IMO, its a small price to pay for being as close to upstream releases as we are with Arch :wink:

**Comment by varlesh** [comment]
I like Antergos - my favorite OS. I believe you )

**Comment by czbaker** [comment]
@lots0logs is definitely right, but...in either sense, it gave me a reason to switch DEs and head over to XFCE, along with switching DMs as well (LXDM).  System is back in order now, I was worried I was going to have to reinstall, which would have sucked.

Either way, I love Antergos and ArchLinux, good stuff.  :)

**Comment by lots0logs** [comment]
Mirrors should all be synced within the next hour or two. Cheers!

**Comment by juliandroid** [comment]
I have three dependency packages failing:

error: failed to prepare transaction (could not satisfy dependencies)
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: light-locker-settings: installing python-gobject (3.20.0-1) breaks dependency 'python-gobject<3.20'
:: lightdm-webkit2-greeter: installing webkit2gtk (2.12.0-2) breaks dependency 'webkit2gtk<2.12'
:: lightdm-webkit2-greeter: installing gtk3 (3.20.2-1) breaks dependency 'gtk3<3.20'

**Comment by victtor** [comment]
Still have the problem... After sync all mirrors.

**Comment by BrasileiroGamer** [comment]
I am following the situation since yesterday. I'm already crazy to reinstall Antergos but this chatinho bug away with my happiness. It seems that now normalized, I saw an update in the repository (https://aur.archlinux.org/packages/lightdm-webkit2-greeter). I'll try to install here, if I succeed notice you.

**Comment by BrasileiroGamer** [comment]
I am following the situation since yesterday. I'm already crazy to reinstall Antergos but this annoying bug away with my happiness. It seems that now normalized, I saw an update in the repository (https://aur.archlinux.org/packages/lightdm-webkit2-greeter). I'll try to install here, if I succeed notice you.

**Comment by voepew** [comment]
@BrasileiroGamer Good for you that you didn't decide to reinstall Antegros because for now it's still not possible to install Antergos.

**Comment by victtor** [comment]
Well guys, it is working now, just sync and update, everything's just fine, cheers.

**Comment by fernandomayer** [comment]
Well, that fixed the dependency error, but after the update, I got the following:

![2016-04-10 20 52 49](https://cloud.githubusercontent.com/assets/650253/14413912/bb86565e-ff5e-11e5-866b-9077b45c9a3b.jpg)

After hitting enter also nothing is showed and I'am unable to login.

**Comment by lots0logs** [comment]
@fernandomayer If you could, please open a new issue and include a [paste2](http://paste2.org) link with the contents of /var/log/lightdm/x-0-greeter.log`. Thanks.

**Comment by ricbermo** [comment]
well, I know it is almost a month old but, I'm still getting this error on a pure Arch installation. Any suggestions of what it could be happening?

**Comment by lots0logs** [comment]
@ricbermo Please open a new issue and include the exact error you are seeing. Thanks.
