### ISSUE TITLE
Host almin-soft.fsay.net is down (affects libreoffice-installer and pacmanxg4)

### ISSUE THREAD

**Issue by mynuta** [Antergos/antergos-packages#99]
libreoffice-installer and pacmanxg4 need to download sources from http://almin-soft.fsay.net. Those PKGBUILDs aren't working

**Comment by karasu** [comment]
As we have octopi and pamac, and we offer libreoffice as an option, maybe
it's time to ditch these packages. What do you think @lots0logs ?

El dijous, 28 d’abril de 2016, mynuta <notifications@github.com> va
escriure:

> libreoffice-installer and pacmanxg4 need to download sources from
> http://almin-soft.fsay.net. Those PKGBUILDs aren't working
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/antergos-packages/issues/99>
>


-- 
Enviat amb el meu Iphone

**Comment by lots0logs** [comment]
Agreed. I've been meaning to remove them but just havent got around to it yet :sweat_smile:
